// -------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_polyphase\fir_ds10_polyphase_tc.v
// Created: 2026-01-07 16:23:34
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fir_ds10_polyphase_tc
// Source Path: fir_ds10_polyphase_tc
// Hierarchy Level: 1
// 
// Master clock enable input: sys_clk_en
// 
// enb_1_1_1   : identical to sys_clk_en
// enb_1_10_1  : 10x slower than sys_clk with phase 1
// 
// -------------------------------------------------------------
module fir_ds10_polyphase_tc
          (sys_clk,
           reset_x,
           sys_clk_en,
           enb_1_1_1,
           enb_1_10_1);


  input   sys_clk;
  input   reset_x;
  input   sys_clk_en;
  output  enb_1_1_1;
  output  enb_1_10_1;


  reg [3:0] count10;  // ufix4
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_10_1_1;


  assign enb_1_1_1 = sys_clk_en;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 9
  always @(posedge sys_clk)
    begin : counter_10_process
      if (reset_x == 1'b0) begin
        count10 <= 4'b0001;
      end
      else begin
        if (sys_clk_en) begin
          if (count10 >= 4'b1001) begin
            count10 <= 4'b0000;
          end
          else begin
            count10 <= count10 + 4'b0001;
          end
        end
      end
    end



  assign comp_1_tmp = count10 == 4'b0000;



  assign phase_1_tmp = comp_1_tmp & sys_clk_en;



  always @(posedge sys_clk)
    begin : phase_delay_process
      if (reset_x == 1'b0) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (sys_clk_en) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end



  assign enb_1_10_1_1 = phase_1 & sys_clk_en;



  assign enb_1_10_1 = enb_1_10_1_1;

endmodule  // fir_ds10_polyphase_tc

