// ------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_polyphase\FIR_Decimation
// Created: 2026-01-07 16:23:35
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// ------------------------------------------------------------
// 
// 
// ------------------------------------------------------------
// 
// Module: FIR_Decimation
// Source Path: /FIR_Decimation
// 
// ------------------------------------------------------------
// 
// HDL Implementation    : Fully parallel
// Multipliers           : 54



module FIR_Decimation
               (
                sys_clk,
                enb_1_1_1,
                reset_x,
                FIR_Decimation_in,
                FIR_Decimation_out
                );

  input   sys_clk; 
  input   enb_1_1_1; 
  input   reset_x; 
  input   signed [15:0] FIR_Decimation_in; //sfix16_En14
  output  signed [31:0] FIR_Decimation_out; //sfix32_En28

////////////////////////////////////////////////////////////////
//Module Architecture: FIR_Decimation
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeffphase1_1 = 16'b1111111010011010; //sfix16_En14
  parameter signed [15:0] coeffphase1_2 = 16'b0000001100111111; //sfix16_En14
  parameter signed [15:0] coeffphase1_3 = 16'b1111101100010110; //sfix16_En14
  parameter signed [15:0] coeffphase1_4 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeffphase1_5 = 16'b1111101100010110; //sfix16_En14
  parameter signed [15:0] coeffphase1_6 = 16'b0000001100111111; //sfix16_En14
  parameter signed [15:0] coeffphase1_7 = 16'b1111111010011010; //sfix16_En14
  parameter signed [15:0] coeffphase2_1 = 16'b1111111010011011; //sfix16_En14
  parameter signed [15:0] coeffphase2_2 = 16'b0000000111101000; //sfix16_En14
  parameter signed [15:0] coeffphase2_3 = 16'b0000000010101000; //sfix16_En14
  parameter signed [15:0] coeffphase2_4 = 16'b0011111010100111; //sfix16_En14
  parameter signed [15:0] coeffphase2_5 = 16'b1111011101011001; //sfix16_En14
  parameter signed [15:0] coeffphase2_6 = 16'b0000001111100101; //sfix16_En14
  parameter signed [15:0] coeffphase2_7 = 16'b0000000000000000; //sfix16_En14
  parameter signed [15:0] coeffphase3_1 = 16'b1111111011101001; //sfix16_En14
  parameter signed [15:0] coeffphase3_2 = 16'b1111111111101100; //sfix16_En14
  parameter signed [15:0] coeffphase3_3 = 16'b0000011111100101; //sfix16_En14
  parameter signed [15:0] coeffphase3_4 = 16'b0011101010111010; //sfix16_En14
  parameter signed [15:0] coeffphase3_5 = 16'b1111010101101101; //sfix16_En14
  parameter signed [15:0] coeffphase3_6 = 16'b0000001111100101; //sfix16_En14
  parameter signed [15:0] coeffphase3_7 = 16'b0000000000000000; //sfix16_En14
  parameter signed [15:0] coeffphase4_1 = 16'b1111111110000110; //sfix16_En14
  parameter signed [15:0] coeffphase4_2 = 16'b1111110101110101; //sfix16_En14
  parameter signed [15:0] coeffphase4_3 = 16'b0001000001110101; //sfix16_En14
  parameter signed [15:0] coeffphase4_4 = 16'b0011010010001000; //sfix16_En14
  parameter signed [15:0] coeffphase4_5 = 16'b1111010100100101; //sfix16_En14
  parameter signed [15:0] coeffphase4_6 = 16'b0000001101011110; //sfix16_En14
  parameter signed [15:0] coeffphase4_7 = 16'b0000000000000000; //sfix16_En14
  parameter signed [15:0] coeffphase5_1 = 16'b0000000001100110; //sfix16_En14
  parameter signed [15:0] coeffphase5_2 = 16'b1111101011000111; //sfix16_En14
  parameter signed [15:0] coeffphase5_3 = 16'b0001100111011001; //sfix16_En14
  parameter signed [15:0] coeffphase5_4 = 16'b0010110010010001; //sfix16_En14
  parameter signed [15:0] coeffphase5_5 = 16'b1111011000110101; //sfix16_En14
  parameter signed [15:0] coeffphase5_6 = 16'b0000001001111100; //sfix16_En14
  parameter signed [15:0] coeffphase5_7 = 16'b0000000000000000; //sfix16_En14
  parameter signed [15:0] coeffphase6_1 = 16'b0000000101101111; //sfix16_En14
  parameter signed [15:0] coeffphase6_2 = 16'b1111100000111001; //sfix16_En14
  parameter signed [15:0] coeffphase6_3 = 16'b0010001101110001; //sfix16_En14
  parameter signed [15:0] coeffphase6_4 = 16'b0010001101110001; //sfix16_En14
  parameter signed [15:0] coeffphase6_5 = 16'b1111100000111001; //sfix16_En14
  parameter signed [15:0] coeffphase6_6 = 16'b0000000101101111; //sfix16_En14
  parameter signed [15:0] coeffphase6_7 = 16'b0000000000000000; //sfix16_En14
  parameter signed [15:0] coeffphase7_1 = 16'b0000001001111100; //sfix16_En14
  parameter signed [15:0] coeffphase7_2 = 16'b1111011000110101; //sfix16_En14
  parameter signed [15:0] coeffphase7_3 = 16'b0010110010010001; //sfix16_En14
  parameter signed [15:0] coeffphase7_4 = 16'b0001100111011001; //sfix16_En14
  parameter signed [15:0] coeffphase7_5 = 16'b1111101011000111; //sfix16_En14
  parameter signed [15:0] coeffphase7_6 = 16'b0000000001100110; //sfix16_En14
  parameter signed [15:0] coeffphase7_7 = 16'b0000000000000000; //sfix16_En14
  parameter signed [15:0] coeffphase8_1 = 16'b0000001101011110; //sfix16_En14
  parameter signed [15:0] coeffphase8_2 = 16'b1111010100100101; //sfix16_En14
  parameter signed [15:0] coeffphase8_3 = 16'b0011010010001000; //sfix16_En14
  parameter signed [15:0] coeffphase8_4 = 16'b0001000001110101; //sfix16_En14
  parameter signed [15:0] coeffphase8_5 = 16'b1111110101110101; //sfix16_En14
  parameter signed [15:0] coeffphase8_6 = 16'b1111111110000110; //sfix16_En14
  parameter signed [15:0] coeffphase8_7 = 16'b0000000000000000; //sfix16_En14
  parameter signed [15:0] coeffphase9_1 = 16'b0000001111100101; //sfix16_En14
  parameter signed [15:0] coeffphase9_2 = 16'b1111010101101101; //sfix16_En14
  parameter signed [15:0] coeffphase9_3 = 16'b0011101010111010; //sfix16_En14
  parameter signed [15:0] coeffphase9_4 = 16'b0000011111100101; //sfix16_En14
  parameter signed [15:0] coeffphase9_5 = 16'b1111111111101100; //sfix16_En14
  parameter signed [15:0] coeffphase9_6 = 16'b1111111011101001; //sfix16_En14
  parameter signed [15:0] coeffphase9_7 = 16'b0000000000000000; //sfix16_En14
  parameter signed [15:0] coeffphase10_1 = 16'b0000001111100101; //sfix16_En14
  parameter signed [15:0] coeffphase10_2 = 16'b1111011101011001; //sfix16_En14
  parameter signed [15:0] coeffphase10_3 = 16'b0011111010100111; //sfix16_En14
  parameter signed [15:0] coeffphase10_4 = 16'b0000000010101000; //sfix16_En14
  parameter signed [15:0] coeffphase10_5 = 16'b0000000111101000; //sfix16_En14
  parameter signed [15:0] coeffphase10_6 = 16'b1111111010011011; //sfix16_En14
  parameter signed [15:0] coeffphase10_7 = 16'b0000000000000000; //sfix16_En14

  // Signals
  reg  [3:0] cur_count; // ufix4
  wire phase_4; // boolean
  wire signed [15:0] input_mux [0:8] ; // sfix16_En14
  reg  signed [15:0] input_pipeline [0:8] ; // sfix16_En14
  wire signed [31:0] product_phase1_4; // sfix32_En28
  wire signed [31:0] product_phase1_4_pipe; // sfix32_En28
  reg  signed [31:0] int_delay_pipe [0:3] ; // sfix32_En28
  wire signed [31:0] product_phase1_5; // sfix32_En28
  reg  signed [31:0] product_phase1_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase1_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase1_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase1_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase1_6; // sfix32_En28
  reg  signed [31:0] product_phase1_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase1_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase1_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase1_6_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase1_7; // sfix32_En28
  reg  signed [31:0] product_phase1_7_pipe; // sfix32_En28
  reg  signed [31:0] product_phase1_7_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase1_7_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase1_7_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase2_1; // sfix32_En28
  reg  signed [31:0] product_phase2_1_pipe; // sfix32_En28
  reg  signed [31:0] product_phase2_1_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase2_1_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase2_1_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase2_2; // sfix32_En28
  reg  signed [31:0] product_phase2_2_pipe; // sfix32_En28
  reg  signed [31:0] product_phase2_2_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase2_2_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase2_2_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase2_3; // sfix32_En28
  reg  signed [31:0] product_phase2_3_pipe; // sfix32_En28
  reg  signed [31:0] product_phase2_3_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase2_3_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase2_3_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase2_4; // sfix32_En28
  reg  signed [31:0] product_phase2_4_pipe; // sfix32_En28
  reg  signed [31:0] product_phase2_4_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase2_4_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase2_4_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase2_5; // sfix32_En28
  reg  signed [31:0] product_phase2_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase2_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase2_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase2_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase2_6; // sfix32_En28
  reg  signed [31:0] product_phase2_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase2_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase2_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase2_6_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase3_1; // sfix32_En28
  reg  signed [31:0] product_phase3_1_pipe; // sfix32_En28
  reg  signed [31:0] product_phase3_1_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase3_1_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase3_1_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase3_2; // sfix32_En28
  reg  signed [31:0] product_phase3_2_pipe; // sfix32_En28
  reg  signed [31:0] product_phase3_2_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase3_2_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase3_2_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase3_3; // sfix32_En28
  reg  signed [31:0] product_phase3_3_pipe; // sfix32_En28
  reg  signed [31:0] product_phase3_3_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase3_3_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase3_3_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase3_4; // sfix32_En28
  reg  signed [31:0] product_phase3_4_pipe; // sfix32_En28
  reg  signed [31:0] product_phase3_4_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase3_4_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase3_4_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase3_5; // sfix32_En28
  reg  signed [31:0] product_phase3_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase3_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase3_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase3_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase3_6; // sfix32_En28
  reg  signed [31:0] product_phase3_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase3_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase3_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase3_6_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase4_1; // sfix32_En28
  reg  signed [31:0] product_phase4_1_pipe; // sfix32_En28
  reg  signed [31:0] product_phase4_1_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase4_1_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase4_1_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase4_2; // sfix32_En28
  reg  signed [31:0] product_phase4_2_pipe; // sfix32_En28
  reg  signed [31:0] product_phase4_2_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase4_2_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase4_2_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase4_3; // sfix32_En28
  reg  signed [31:0] product_phase4_3_pipe; // sfix32_En28
  reg  signed [31:0] product_phase4_3_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase4_3_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase4_3_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase4_4; // sfix32_En28
  reg  signed [31:0] product_phase4_4_pipe; // sfix32_En28
  reg  signed [31:0] product_phase4_4_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase4_4_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase4_4_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase4_5; // sfix32_En28
  reg  signed [31:0] product_phase4_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase4_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase4_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase4_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase4_6; // sfix32_En28
  reg  signed [31:0] product_phase4_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase4_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase4_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase4_6_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase5_1; // sfix32_En28
  reg  signed [31:0] product_phase5_1_pipe; // sfix32_En28
  reg  signed [31:0] product_phase5_1_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase5_1_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase5_1_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase5_2; // sfix32_En28
  reg  signed [31:0] product_phase5_2_pipe; // sfix32_En28
  reg  signed [31:0] product_phase5_2_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase5_2_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase5_2_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase5_3; // sfix32_En28
  reg  signed [31:0] product_phase5_3_pipe; // sfix32_En28
  reg  signed [31:0] product_phase5_3_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase5_3_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase5_3_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase5_4; // sfix32_En28
  reg  signed [31:0] product_phase5_4_pipe; // sfix32_En28
  reg  signed [31:0] product_phase5_4_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase5_4_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase5_4_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase5_5; // sfix32_En28
  reg  signed [31:0] product_phase5_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase5_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase5_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase5_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase5_6; // sfix32_En28
  reg  signed [31:0] product_phase5_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase5_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase5_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase5_6_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase6_4; // sfix32_En28
  reg  signed [31:0] product_phase6_4_pipe; // sfix32_En28
  reg  signed [31:0] product_phase6_4_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase6_4_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase6_4_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase6_5; // sfix32_En28
  reg  signed [31:0] product_phase6_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase6_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase6_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase6_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase6_6; // sfix32_En28
  reg  signed [31:0] product_phase6_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase6_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase6_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase6_6_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase7_1; // sfix32_En28
  reg  signed [31:0] product_phase7_1_pipe; // sfix32_En28
  reg  signed [31:0] product_phase7_1_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase7_1_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase7_1_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase7_2; // sfix32_En28
  reg  signed [31:0] product_phase7_2_pipe; // sfix32_En28
  reg  signed [31:0] product_phase7_2_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase7_2_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase7_2_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase7_3; // sfix32_En28
  reg  signed [31:0] product_phase7_3_pipe; // sfix32_En28
  reg  signed [31:0] product_phase7_3_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase7_3_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase7_3_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase7_4; // sfix32_En28
  reg  signed [31:0] product_phase7_4_pipe; // sfix32_En28
  reg  signed [31:0] product_phase7_4_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase7_4_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase7_4_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase7_5; // sfix32_En28
  reg  signed [31:0] product_phase7_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase7_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase7_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase7_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase7_6; // sfix32_En28
  reg  signed [31:0] product_phase7_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase7_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase7_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase7_6_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase8_1; // sfix32_En28
  reg  signed [31:0] product_phase8_1_pipe; // sfix32_En28
  reg  signed [31:0] product_phase8_1_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase8_1_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase8_1_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase8_2; // sfix32_En28
  reg  signed [31:0] product_phase8_2_pipe; // sfix32_En28
  reg  signed [31:0] product_phase8_2_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase8_2_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase8_2_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase8_3; // sfix32_En28
  reg  signed [31:0] product_phase8_3_pipe; // sfix32_En28
  reg  signed [31:0] product_phase8_3_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase8_3_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase8_3_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase8_4; // sfix32_En28
  reg  signed [31:0] product_phase8_4_pipe; // sfix32_En28
  reg  signed [31:0] product_phase8_4_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase8_4_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase8_4_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase8_5; // sfix32_En28
  reg  signed [31:0] product_phase8_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase8_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase8_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase8_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase8_6; // sfix32_En28
  reg  signed [31:0] product_phase8_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase8_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase8_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase8_6_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase9_1; // sfix32_En28
  reg  signed [31:0] product_phase9_1_pipe; // sfix32_En28
  reg  signed [31:0] product_phase9_1_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase9_1_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase9_1_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase9_2; // sfix32_En28
  reg  signed [31:0] product_phase9_2_pipe; // sfix32_En28
  reg  signed [31:0] product_phase9_2_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase9_2_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase9_2_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase9_3; // sfix32_En28
  reg  signed [31:0] product_phase9_3_pipe; // sfix32_En28
  reg  signed [31:0] product_phase9_3_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase9_3_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase9_3_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase9_4; // sfix32_En28
  reg  signed [31:0] product_phase9_4_pipe; // sfix32_En28
  reg  signed [31:0] product_phase9_4_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase9_4_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase9_4_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase9_5; // sfix32_En28
  reg  signed [31:0] product_phase9_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase9_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase9_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase9_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase9_6; // sfix32_En28
  reg  signed [31:0] product_phase9_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase9_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase9_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase9_6_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase10_1; // sfix32_En28
  reg  signed [31:0] product_phase10_1_pipe; // sfix32_En28
  reg  signed [31:0] product_phase10_1_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase10_1_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase10_1_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase10_2; // sfix32_En28
  reg  signed [31:0] product_phase10_2_pipe; // sfix32_En28
  reg  signed [31:0] product_phase10_2_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase10_2_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase10_2_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase10_3; // sfix32_En28
  reg  signed [31:0] product_phase10_3_pipe; // sfix32_En28
  reg  signed [31:0] product_phase10_3_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase10_3_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase10_3_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase10_4; // sfix32_En28
  reg  signed [31:0] product_phase10_4_pipe; // sfix32_En28
  reg  signed [31:0] product_phase10_4_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase10_4_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase10_4_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase10_5; // sfix32_En28
  reg  signed [31:0] product_phase10_5_pipe; // sfix32_En28
  reg  signed [31:0] product_phase10_5_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase10_5_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase10_5_pipe_3; // sfix32_En28
  wire signed [31:0] product_phase10_6; // sfix32_En28
  reg  signed [31:0] product_phase10_6_pipe; // sfix32_En28
  reg  signed [31:0] product_phase10_6_pipe_1; // sfix32_En28
  reg  signed [31:0] product_phase10_6_pipe_2; // sfix32_En28
  reg  signed [31:0] product_phase10_6_pipe_3; // sfix32_En28
  wire signed [34:0] polyadd_1; // sfix35_En28
  wire signed [34:0] add_cast; // sfix35_En28
  wire signed [34:0] add_cast_1; // sfix35_En28
  wire signed [35:0] add_temp; // sfix36_En28
  wire signed [34:0] polyadd_1_1; // sfix35_En28
  wire signed [34:0] add_cast_2; // sfix35_En28
  wire signed [34:0] add_cast_3; // sfix35_En28
  wire signed [35:0] add_temp_1; // sfix36_En28
  wire signed [34:0] polyadd_1_2; // sfix35_En28
  wire signed [34:0] add_cast_4; // sfix35_En28
  wire signed [34:0] add_cast_5; // sfix35_En28
  wire signed [35:0] add_temp_2; // sfix36_En28
  wire signed [34:0] polyadd_1_3; // sfix35_En28
  wire signed [34:0] add_cast_6; // sfix35_En28
  wire signed [34:0] add_cast_7; // sfix35_En28
  wire signed [35:0] add_temp_3; // sfix36_En28
  wire signed [34:0] polyadd_1_4; // sfix35_En28
  wire signed [34:0] add_cast_8; // sfix35_En28
  wire signed [34:0] add_cast_9; // sfix35_En28
  wire signed [35:0] add_temp_4; // sfix36_En28
  wire signed [34:0] polyadd_1_5; // sfix35_En28
  wire signed [34:0] add_cast_10; // sfix35_En28
  wire signed [34:0] add_cast_11; // sfix35_En28
  wire signed [35:0] add_temp_5; // sfix36_En28
  wire signed [34:0] polyadd_1_6; // sfix35_En28
  wire signed [34:0] add_cast_12; // sfix35_En28
  wire signed [34:0] add_cast_13; // sfix35_En28
  wire signed [35:0] add_temp_6; // sfix36_En28
  wire signed [34:0] polyadd_1_7; // sfix35_En28
  wire signed [34:0] add_cast_14; // sfix35_En28
  wire signed [34:0] add_cast_15; // sfix35_En28
  wire signed [35:0] add_temp_7; // sfix36_En28
  wire signed [34:0] polyadd_1_8; // sfix35_En28
  wire signed [34:0] add_cast_16; // sfix35_En28
  wire signed [34:0] add_cast_17; // sfix35_En28
  wire signed [35:0] add_temp_8; // sfix36_En28
  wire signed [34:0] polyadd_2; // sfix35_En28
  wire signed [34:0] add_cast_18; // sfix35_En28
  wire signed [34:0] add_cast_19; // sfix35_En28
  wire signed [35:0] add_temp_9; // sfix36_En28
  wire signed [34:0] polyadd_2_1; // sfix35_En28
  wire signed [34:0] add_cast_20; // sfix35_En28
  wire signed [34:0] add_cast_21; // sfix35_En28
  wire signed [35:0] add_temp_10; // sfix36_En28
  wire signed [34:0] polyadd_2_2; // sfix35_En28
  wire signed [34:0] add_cast_22; // sfix35_En28
  wire signed [34:0] add_cast_23; // sfix35_En28
  wire signed [35:0] add_temp_11; // sfix36_En28
  wire signed [34:0] polyadd_2_3; // sfix35_En28
  wire signed [34:0] add_cast_24; // sfix35_En28
  wire signed [34:0] add_cast_25; // sfix35_En28
  wire signed [35:0] add_temp_12; // sfix36_En28
  wire signed [34:0] polyadd_2_4; // sfix35_En28
  wire signed [34:0] add_cast_26; // sfix35_En28
  wire signed [34:0] add_cast_27; // sfix35_En28
  wire signed [35:0] add_temp_13; // sfix36_En28
  wire signed [34:0] polyadd_2_5; // sfix35_En28
  wire signed [34:0] add_cast_28; // sfix35_En28
  wire signed [34:0] add_cast_29; // sfix35_En28
  wire signed [35:0] add_temp_14; // sfix36_En28
  wire signed [34:0] polyadd_2_6; // sfix35_En28
  wire signed [34:0] add_cast_30; // sfix35_En28
  wire signed [34:0] add_cast_31; // sfix35_En28
  wire signed [35:0] add_temp_15; // sfix36_En28
  wire signed [34:0] polyadd_2_7; // sfix35_En28
  wire signed [34:0] add_cast_32; // sfix35_En28
  wire signed [34:0] add_cast_33; // sfix35_En28
  wire signed [35:0] add_temp_16; // sfix36_En28
  wire signed [34:0] polyadd_2_8; // sfix35_En28
  wire signed [34:0] add_cast_34; // sfix35_En28
  wire signed [34:0] add_cast_35; // sfix35_En28
  wire signed [35:0] add_temp_17; // sfix36_En28
  wire signed [34:0] polyadd_3; // sfix35_En28
  wire signed [34:0] add_cast_36; // sfix35_En28
  wire signed [34:0] add_cast_37; // sfix35_En28
  wire signed [35:0] add_temp_18; // sfix36_En28
  wire signed [34:0] polyadd_3_1; // sfix35_En28
  wire signed [34:0] add_cast_38; // sfix35_En28
  wire signed [34:0] add_cast_39; // sfix35_En28
  wire signed [35:0] add_temp_19; // sfix36_En28
  wire signed [34:0] polyadd_3_2; // sfix35_En28
  wire signed [34:0] add_cast_40; // sfix35_En28
  wire signed [34:0] add_cast_41; // sfix35_En28
  wire signed [35:0] add_temp_20; // sfix36_En28
  wire signed [34:0] polyadd_3_3; // sfix35_En28
  wire signed [34:0] add_cast_42; // sfix35_En28
  wire signed [34:0] add_cast_43; // sfix35_En28
  wire signed [35:0] add_temp_21; // sfix36_En28
  wire signed [34:0] polyadd_3_4; // sfix35_En28
  wire signed [34:0] add_cast_44; // sfix35_En28
  wire signed [34:0] add_cast_45; // sfix35_En28
  wire signed [35:0] add_temp_22; // sfix36_En28
  wire signed [34:0] polyadd_3_5; // sfix35_En28
  wire signed [34:0] add_cast_46; // sfix35_En28
  wire signed [34:0] add_cast_47; // sfix35_En28
  wire signed [35:0] add_temp_23; // sfix36_En28
  wire signed [34:0] polyadd_3_6; // sfix35_En28
  wire signed [34:0] add_cast_48; // sfix35_En28
  wire signed [34:0] add_cast_49; // sfix35_En28
  wire signed [35:0] add_temp_24; // sfix36_En28
  wire signed [34:0] polyadd_3_7; // sfix35_En28
  wire signed [34:0] add_cast_50; // sfix35_En28
  wire signed [34:0] add_cast_51; // sfix35_En28
  wire signed [35:0] add_temp_25; // sfix36_En28
  wire signed [34:0] polyadd_3_8; // sfix35_En28
  wire signed [34:0] add_cast_52; // sfix35_En28
  wire signed [34:0] add_cast_53; // sfix35_En28
  wire signed [35:0] add_temp_26; // sfix36_En28
  wire signed [34:0] polyadd_4; // sfix35_En28
  wire signed [34:0] add_cast_54; // sfix35_En28
  wire signed [34:0] add_cast_55; // sfix35_En28
  wire signed [35:0] add_temp_27; // sfix36_En28
  wire signed [34:0] polyadd_4_1; // sfix35_En28
  wire signed [34:0] add_cast_56; // sfix35_En28
  wire signed [34:0] add_cast_57; // sfix35_En28
  wire signed [35:0] add_temp_28; // sfix36_En28
  wire signed [34:0] polyadd_4_2; // sfix35_En28
  wire signed [34:0] add_cast_58; // sfix35_En28
  wire signed [34:0] add_cast_59; // sfix35_En28
  wire signed [35:0] add_temp_29; // sfix36_En28
  wire signed [34:0] polyadd_4_3; // sfix35_En28
  wire signed [34:0] add_cast_60; // sfix35_En28
  wire signed [34:0] add_cast_61; // sfix35_En28
  wire signed [35:0] add_temp_30; // sfix36_En28
  wire signed [34:0] polyadd_4_4; // sfix35_En28
  wire signed [34:0] add_cast_62; // sfix35_En28
  wire signed [34:0] add_cast_63; // sfix35_En28
  wire signed [35:0] add_temp_31; // sfix36_En28
  wire signed [34:0] polyadd_4_5; // sfix35_En28
  wire signed [34:0] add_cast_64; // sfix35_En28
  wire signed [34:0] add_cast_65; // sfix35_En28
  wire signed [35:0] add_temp_32; // sfix36_En28
  wire signed [34:0] polyadd_4_6; // sfix35_En28
  wire signed [34:0] add_cast_66; // sfix35_En28
  wire signed [34:0] add_cast_67; // sfix35_En28
  wire signed [35:0] add_temp_33; // sfix36_En28
  wire signed [34:0] polyadd_4_7; // sfix35_En28
  wire signed [34:0] add_cast_68; // sfix35_En28
  wire signed [34:0] add_cast_69; // sfix35_En28
  wire signed [35:0] add_temp_34; // sfix36_En28
  wire signed [34:0] polyadd_4_8; // sfix35_En28
  wire signed [34:0] add_cast_70; // sfix35_En28
  wire signed [34:0] add_cast_71; // sfix35_En28
  wire signed [35:0] add_temp_35; // sfix36_En28
  wire signed [34:0] polyadd_5; // sfix35_En28
  wire signed [34:0] add_cast_72; // sfix35_En28
  wire signed [34:0] add_cast_73; // sfix35_En28
  wire signed [35:0] add_temp_36; // sfix36_En28
  wire signed [34:0] polyadd_5_1; // sfix35_En28
  wire signed [34:0] add_cast_74; // sfix35_En28
  wire signed [34:0] add_cast_75; // sfix35_En28
  wire signed [35:0] add_temp_37; // sfix36_En28
  wire signed [34:0] polyadd_5_2; // sfix35_En28
  wire signed [34:0] add_cast_76; // sfix35_En28
  wire signed [34:0] add_cast_77; // sfix35_En28
  wire signed [35:0] add_temp_38; // sfix36_En28
  wire signed [34:0] polyadd_5_3; // sfix35_En28
  wire signed [34:0] add_cast_78; // sfix35_En28
  wire signed [34:0] add_cast_79; // sfix35_En28
  wire signed [35:0] add_temp_39; // sfix36_En28
  wire signed [34:0] polyadd_5_4; // sfix35_En28
  wire signed [34:0] add_cast_80; // sfix35_En28
  wire signed [34:0] add_cast_81; // sfix35_En28
  wire signed [35:0] add_temp_40; // sfix36_En28
  wire signed [34:0] polyadd_5_5; // sfix35_En28
  wire signed [34:0] add_cast_82; // sfix35_En28
  wire signed [34:0] add_cast_83; // sfix35_En28
  wire signed [35:0] add_temp_41; // sfix36_En28
  wire signed [34:0] polyadd_5_6; // sfix35_En28
  wire signed [34:0] add_cast_84; // sfix35_En28
  wire signed [34:0] add_cast_85; // sfix35_En28
  wire signed [35:0] add_temp_42; // sfix36_En28
  wire signed [34:0] polyadd_5_7; // sfix35_En28
  wire signed [34:0] add_cast_86; // sfix35_En28
  wire signed [34:0] add_cast_87; // sfix35_En28
  wire signed [35:0] add_temp_43; // sfix36_En28
  wire signed [34:0] polyadd_5_8; // sfix35_En28
  wire signed [34:0] add_cast_88; // sfix35_En28
  wire signed [34:0] add_cast_89; // sfix35_En28
  wire signed [35:0] add_temp_44; // sfix36_En28
  wire signed [34:0] polyadd_6; // sfix35_En28
  wire signed [34:0] add_cast_90; // sfix35_En28
  wire signed [34:0] add_cast_91; // sfix35_En28
  wire signed [35:0] add_temp_45; // sfix36_En28
  wire signed [34:0] polyadd_6_1; // sfix35_En28
  wire signed [34:0] add_cast_92; // sfix35_En28
  wire signed [34:0] add_cast_93; // sfix35_En28
  wire signed [35:0] add_temp_46; // sfix36_En28
  wire signed [34:0] polyadd_6_2; // sfix35_En28
  wire signed [34:0] add_cast_94; // sfix35_En28
  wire signed [34:0] add_cast_95; // sfix35_En28
  wire signed [35:0] add_temp_47; // sfix36_En28
  wire signed [34:0] polyadd_6_3; // sfix35_En28
  wire signed [34:0] add_cast_96; // sfix35_En28
  wire signed [34:0] add_cast_97; // sfix35_En28
  wire signed [35:0] add_temp_48; // sfix36_En28
  wire signed [34:0] polyadd_6_4; // sfix35_En28
  wire signed [34:0] add_cast_98; // sfix35_En28
  wire signed [34:0] add_cast_99; // sfix35_En28
  wire signed [35:0] add_temp_49; // sfix36_En28
  wire signed [34:0] polyadd_6_5; // sfix35_En28
  wire signed [34:0] add_cast_100; // sfix35_En28
  wire signed [34:0] add_cast_101; // sfix35_En28
  wire signed [35:0] add_temp_50; // sfix36_En28
  wire signed [34:0] polyadd_6_6; // sfix35_En28
  wire signed [34:0] add_cast_102; // sfix35_En28
  wire signed [34:0] add_cast_103; // sfix35_En28
  wire signed [35:0] add_temp_51; // sfix36_En28
  wire signed [34:0] polyadd_6_7; // sfix35_En28
  wire signed [34:0] add_cast_104; // sfix35_En28
  wire signed [34:0] add_cast_105; // sfix35_En28
  wire signed [35:0] add_temp_52; // sfix36_En28
  wire signed [34:0] polyadd_6_8; // sfix35_En28
  wire signed [34:0] add_cast_106; // sfix35_En28
  wire signed [34:0] add_cast_107; // sfix35_En28
  wire signed [35:0] add_temp_53; // sfix36_En28
  wire signed [34:0] polyadd_7; // sfix35_En28
  reg  signed [34:0] delay_pipeline [0:5] ; // sfix35_En28
  wire signed [34:0] sumvector [0:5] ; // sfix35_En28
  wire signed [34:0] finalsum; // sfix35_En28
  wire signed [34:0] add_cast_108; // sfix35_En28
  wire signed [34:0] add_cast_109; // sfix35_En28
  wire signed [35:0] add_temp_54; // sfix36_En28
  wire signed [34:0] add_cast_110; // sfix35_En28
  wire signed [34:0] add_cast_111; // sfix35_En28
  wire signed [35:0] add_temp_55; // sfix36_En28
  wire signed [34:0] add_cast_112; // sfix35_En28
  wire signed [34:0] add_cast_113; // sfix35_En28
  wire signed [35:0] add_temp_56; // sfix36_En28
  wire signed [34:0] add_cast_114; // sfix35_En28
  wire signed [34:0] add_cast_115; // sfix35_En28
  wire signed [35:0] add_temp_57; // sfix36_En28
  wire signed [34:0] add_cast_116; // sfix35_En28
  wire signed [34:0] add_cast_117; // sfix35_En28
  wire signed [35:0] add_temp_58; // sfix36_En28
  wire signed [34:0] add_cast_118; // sfix35_En28
  wire signed [34:0] add_cast_119; // sfix35_En28
  wire signed [35:0] add_temp_59; // sfix36_En28
  wire signed [31:0] output_typeconvert; // sfix32_En28
  reg  signed [31:0] regout; // sfix32_En28
  wire signed [31:0] muxout; // sfix32_En28

  // Block Statements
  always @ (posedge sys_clk)
    begin: ce_output
      if (reset_x == 1'b0) begin
        cur_count <= 4'b0000;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin
          if (cur_count >= 4'b1001) begin
            cur_count <= 4'b0000;
          end
          else begin
            cur_count <= cur_count + 4'b0001;
          end
        end
      end
    end // ce_output

  assign  phase_4 = (cur_count == 4'b0100 && enb_1_1_1 == 1'b1) ? 1'b1 : 1'b0;

  //   ---------------- Input Registers ----------------

  assign input_mux[0] = (cur_count == 4'b1001) ? FIR_Decimation_in :
                  input_pipeline[0];
  assign input_mux[1] = (cur_count == 4'b1000) ? FIR_Decimation_in :
                  input_pipeline[1];
  assign input_mux[2] = (cur_count == 4'b0111) ? FIR_Decimation_in :
                  input_pipeline[2];
  assign input_mux[3] = (cur_count == 4'b0110) ? FIR_Decimation_in :
                  input_pipeline[3];
  assign input_mux[4] = (cur_count == 4'b0101) ? FIR_Decimation_in :
                  input_pipeline[4];
  assign input_mux[5] = (cur_count == 4'b0100) ? FIR_Decimation_in :
                  input_pipeline[5];
  assign input_mux[6] = (cur_count == 4'b0011) ? FIR_Decimation_in :
                  input_pipeline[6];
  assign input_mux[7] = (cur_count == 4'b0010) ? FIR_Decimation_in :
                  input_pipeline[7];
  assign input_mux[8] = (cur_count == 4'b0001) ? FIR_Decimation_in :
                  input_pipeline[8];
  always @ ( posedge sys_clk)
    begin: input_pipeline_process9
      if (reset_x == 1'b0) begin
        input_pipeline[0] <= 0;
        input_pipeline[1] <= 0;
        input_pipeline[2] <= 0;
        input_pipeline[3] <= 0;
        input_pipeline[4] <= 0;
        input_pipeline[5] <= 0;
        input_pipeline[6] <= 0;
        input_pipeline[7] <= 0;
        input_pipeline[8] <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin
          input_pipeline[0] <= input_mux[0];
          input_pipeline[1] <= input_mux[1];
          input_pipeline[2] <= input_mux[2];
          input_pipeline[3] <= input_mux[3];
          input_pipeline[4] <= input_mux[4];
          input_pipeline[5] <= input_mux[5];
          input_pipeline[6] <= input_mux[6];
          input_pipeline[7] <= input_mux[7];
          input_pipeline[8] <= input_mux[8];
        end
      end
    end // input_pipeline_process9

  always @ (posedge sys_clk)
    begin: temp_process1
      if (reset_x == 1'b0) begin
        int_delay_pipe[0] <= 32'h00000000;
        int_delay_pipe[1] <= 32'h00000000;
        int_delay_pipe[2] <= 32'h00000000;
        int_delay_pipe[3] <= 32'h00000000;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin
          int_delay_pipe[1] <= int_delay_pipe[0];
          int_delay_pipe[2] <= int_delay_pipe[1];
          int_delay_pipe[3] <= int_delay_pipe[2];
          int_delay_pipe[0] <= product_phase1_4_pipe;
        end
      end
    end // temp_process1
  assign product_phase1_4 = int_delay_pipe[3];

  assign product_phase1_4_pipe = $signed({FIR_Decimation_in[15:0], 14'b00000000000000});

  always @ (posedge sys_clk)
    begin: temp_process2
      if (reset_x == 1'b0) begin
        product_phase1_5_pipe <= 0;
        product_phase1_5_pipe_1 <= 0;
        product_phase1_5_pipe_2 <= 0;
        product_phase1_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase1_5_pipe <= FIR_Decimation_in * coeffphase1_5;

          product_phase1_5_pipe_1 <= product_phase1_5_pipe;
          product_phase1_5_pipe_2 <= product_phase1_5_pipe_1;
          product_phase1_5_pipe_3 <= product_phase1_5_pipe_2;
        end
      end
    end // temp_process2

  assign product_phase1_5 = product_phase1_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process3
      if (reset_x == 1'b0) begin
        product_phase1_6_pipe <= 0;
        product_phase1_6_pipe_1 <= 0;
        product_phase1_6_pipe_2 <= 0;
        product_phase1_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase1_6_pipe <= FIR_Decimation_in * coeffphase1_6;

          product_phase1_6_pipe_1 <= product_phase1_6_pipe;
          product_phase1_6_pipe_2 <= product_phase1_6_pipe_1;
          product_phase1_6_pipe_3 <= product_phase1_6_pipe_2;
        end
      end
    end // temp_process3

  assign product_phase1_6 = product_phase1_6_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process4
      if (reset_x == 1'b0) begin
        product_phase1_7_pipe <= 0;
        product_phase1_7_pipe_1 <= 0;
        product_phase1_7_pipe_2 <= 0;
        product_phase1_7_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase1_7_pipe <= FIR_Decimation_in * coeffphase1_7;

          product_phase1_7_pipe_1 <= product_phase1_7_pipe;
          product_phase1_7_pipe_2 <= product_phase1_7_pipe_1;
          product_phase1_7_pipe_3 <= product_phase1_7_pipe_2;
        end
      end
    end // temp_process4

  assign product_phase1_7 = product_phase1_7_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process5
      if (reset_x == 1'b0) begin
        product_phase2_1_pipe <= 0;
        product_phase2_1_pipe_1 <= 0;
        product_phase2_1_pipe_2 <= 0;
        product_phase2_1_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase2_1_pipe <= input_pipeline[0] * coeffphase2_1;

          product_phase2_1_pipe_1 <= product_phase2_1_pipe;
          product_phase2_1_pipe_2 <= product_phase2_1_pipe_1;
          product_phase2_1_pipe_3 <= product_phase2_1_pipe_2;
        end
      end
    end // temp_process5

  assign product_phase2_1 = product_phase2_1_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process6
      if (reset_x == 1'b0) begin
        product_phase2_2_pipe <= 0;
        product_phase2_2_pipe_1 <= 0;
        product_phase2_2_pipe_2 <= 0;
        product_phase2_2_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase2_2_pipe <= input_pipeline[0] * coeffphase2_2;

          product_phase2_2_pipe_1 <= product_phase2_2_pipe;
          product_phase2_2_pipe_2 <= product_phase2_2_pipe_1;
          product_phase2_2_pipe_3 <= product_phase2_2_pipe_2;
        end
      end
    end // temp_process6

  assign product_phase2_2 = product_phase2_2_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process7
      if (reset_x == 1'b0) begin
        product_phase2_3_pipe <= 0;
        product_phase2_3_pipe_1 <= 0;
        product_phase2_3_pipe_2 <= 0;
        product_phase2_3_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase2_3_pipe <= input_pipeline[0] * coeffphase2_3;

          product_phase2_3_pipe_1 <= product_phase2_3_pipe;
          product_phase2_3_pipe_2 <= product_phase2_3_pipe_1;
          product_phase2_3_pipe_3 <= product_phase2_3_pipe_2;
        end
      end
    end // temp_process7

  assign product_phase2_3 = product_phase2_3_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process8
      if (reset_x == 1'b0) begin
        product_phase2_4_pipe <= 0;
        product_phase2_4_pipe_1 <= 0;
        product_phase2_4_pipe_2 <= 0;
        product_phase2_4_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase2_4_pipe <= input_pipeline[0] * coeffphase2_4;

          product_phase2_4_pipe_1 <= product_phase2_4_pipe;
          product_phase2_4_pipe_2 <= product_phase2_4_pipe_1;
          product_phase2_4_pipe_3 <= product_phase2_4_pipe_2;
        end
      end
    end // temp_process8

  assign product_phase2_4 = product_phase2_4_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process9
      if (reset_x == 1'b0) begin
        product_phase2_5_pipe <= 0;
        product_phase2_5_pipe_1 <= 0;
        product_phase2_5_pipe_2 <= 0;
        product_phase2_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase2_5_pipe <= input_pipeline[0] * coeffphase2_5;

          product_phase2_5_pipe_1 <= product_phase2_5_pipe;
          product_phase2_5_pipe_2 <= product_phase2_5_pipe_1;
          product_phase2_5_pipe_3 <= product_phase2_5_pipe_2;
        end
      end
    end // temp_process9

  assign product_phase2_5 = product_phase2_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process10
      if (reset_x == 1'b0) begin
        product_phase2_6_pipe <= 0;
        product_phase2_6_pipe_1 <= 0;
        product_phase2_6_pipe_2 <= 0;
        product_phase2_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase2_6_pipe <= input_pipeline[0] * coeffphase2_6;

          product_phase2_6_pipe_1 <= product_phase2_6_pipe;
          product_phase2_6_pipe_2 <= product_phase2_6_pipe_1;
          product_phase2_6_pipe_3 <= product_phase2_6_pipe_2;
        end
      end
    end // temp_process10

  assign product_phase2_6 = product_phase2_6_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process11
      if (reset_x == 1'b0) begin
        product_phase3_1_pipe <= 0;
        product_phase3_1_pipe_1 <= 0;
        product_phase3_1_pipe_2 <= 0;
        product_phase3_1_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase3_1_pipe <= input_pipeline[1] * coeffphase3_1;

          product_phase3_1_pipe_1 <= product_phase3_1_pipe;
          product_phase3_1_pipe_2 <= product_phase3_1_pipe_1;
          product_phase3_1_pipe_3 <= product_phase3_1_pipe_2;
        end
      end
    end // temp_process11

  assign product_phase3_1 = product_phase3_1_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process12
      if (reset_x == 1'b0) begin
        product_phase3_2_pipe <= 0;
        product_phase3_2_pipe_1 <= 0;
        product_phase3_2_pipe_2 <= 0;
        product_phase3_2_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase3_2_pipe <= input_pipeline[1] * coeffphase3_2;

          product_phase3_2_pipe_1 <= product_phase3_2_pipe;
          product_phase3_2_pipe_2 <= product_phase3_2_pipe_1;
          product_phase3_2_pipe_3 <= product_phase3_2_pipe_2;
        end
      end
    end // temp_process12

  assign product_phase3_2 = product_phase3_2_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process13
      if (reset_x == 1'b0) begin
        product_phase3_3_pipe <= 0;
        product_phase3_3_pipe_1 <= 0;
        product_phase3_3_pipe_2 <= 0;
        product_phase3_3_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase3_3_pipe <= input_pipeline[1] * coeffphase3_3;

          product_phase3_3_pipe_1 <= product_phase3_3_pipe;
          product_phase3_3_pipe_2 <= product_phase3_3_pipe_1;
          product_phase3_3_pipe_3 <= product_phase3_3_pipe_2;
        end
      end
    end // temp_process13

  assign product_phase3_3 = product_phase3_3_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process14
      if (reset_x == 1'b0) begin
        product_phase3_4_pipe <= 0;
        product_phase3_4_pipe_1 <= 0;
        product_phase3_4_pipe_2 <= 0;
        product_phase3_4_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase3_4_pipe <= input_pipeline[1] * coeffphase3_4;

          product_phase3_4_pipe_1 <= product_phase3_4_pipe;
          product_phase3_4_pipe_2 <= product_phase3_4_pipe_1;
          product_phase3_4_pipe_3 <= product_phase3_4_pipe_2;
        end
      end
    end // temp_process14

  assign product_phase3_4 = product_phase3_4_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process15
      if (reset_x == 1'b0) begin
        product_phase3_5_pipe <= 0;
        product_phase3_5_pipe_1 <= 0;
        product_phase3_5_pipe_2 <= 0;
        product_phase3_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase3_5_pipe <= input_pipeline[1] * coeffphase3_5;

          product_phase3_5_pipe_1 <= product_phase3_5_pipe;
          product_phase3_5_pipe_2 <= product_phase3_5_pipe_1;
          product_phase3_5_pipe_3 <= product_phase3_5_pipe_2;
        end
      end
    end // temp_process15

  assign product_phase3_5 = product_phase3_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process16
      if (reset_x == 1'b0) begin
        product_phase3_6_pipe <= 0;
        product_phase3_6_pipe_1 <= 0;
        product_phase3_6_pipe_2 <= 0;
        product_phase3_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase3_6_pipe <= input_pipeline[1] * coeffphase3_6;

          product_phase3_6_pipe_1 <= product_phase3_6_pipe;
          product_phase3_6_pipe_2 <= product_phase3_6_pipe_1;
          product_phase3_6_pipe_3 <= product_phase3_6_pipe_2;
        end
      end
    end // temp_process16

  assign product_phase3_6 = product_phase3_6_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process17
      if (reset_x == 1'b0) begin
        product_phase4_1_pipe <= 0;
        product_phase4_1_pipe_1 <= 0;
        product_phase4_1_pipe_2 <= 0;
        product_phase4_1_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase4_1_pipe <= input_pipeline[2] * coeffphase4_1;

          product_phase4_1_pipe_1 <= product_phase4_1_pipe;
          product_phase4_1_pipe_2 <= product_phase4_1_pipe_1;
          product_phase4_1_pipe_3 <= product_phase4_1_pipe_2;
        end
      end
    end // temp_process17

  assign product_phase4_1 = product_phase4_1_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process18
      if (reset_x == 1'b0) begin
        product_phase4_2_pipe <= 0;
        product_phase4_2_pipe_1 <= 0;
        product_phase4_2_pipe_2 <= 0;
        product_phase4_2_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase4_2_pipe <= input_pipeline[2] * coeffphase4_2;

          product_phase4_2_pipe_1 <= product_phase4_2_pipe;
          product_phase4_2_pipe_2 <= product_phase4_2_pipe_1;
          product_phase4_2_pipe_3 <= product_phase4_2_pipe_2;
        end
      end
    end // temp_process18

  assign product_phase4_2 = product_phase4_2_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process19
      if (reset_x == 1'b0) begin
        product_phase4_3_pipe <= 0;
        product_phase4_3_pipe_1 <= 0;
        product_phase4_3_pipe_2 <= 0;
        product_phase4_3_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase4_3_pipe <= input_pipeline[2] * coeffphase4_3;

          product_phase4_3_pipe_1 <= product_phase4_3_pipe;
          product_phase4_3_pipe_2 <= product_phase4_3_pipe_1;
          product_phase4_3_pipe_3 <= product_phase4_3_pipe_2;
        end
      end
    end // temp_process19

  assign product_phase4_3 = product_phase4_3_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process20
      if (reset_x == 1'b0) begin
        product_phase4_4_pipe <= 0;
        product_phase4_4_pipe_1 <= 0;
        product_phase4_4_pipe_2 <= 0;
        product_phase4_4_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase4_4_pipe <= input_pipeline[2] * coeffphase4_4;

          product_phase4_4_pipe_1 <= product_phase4_4_pipe;
          product_phase4_4_pipe_2 <= product_phase4_4_pipe_1;
          product_phase4_4_pipe_3 <= product_phase4_4_pipe_2;
        end
      end
    end // temp_process20

  assign product_phase4_4 = product_phase4_4_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process21
      if (reset_x == 1'b0) begin
        product_phase4_5_pipe <= 0;
        product_phase4_5_pipe_1 <= 0;
        product_phase4_5_pipe_2 <= 0;
        product_phase4_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase4_5_pipe <= input_pipeline[2] * coeffphase4_5;

          product_phase4_5_pipe_1 <= product_phase4_5_pipe;
          product_phase4_5_pipe_2 <= product_phase4_5_pipe_1;
          product_phase4_5_pipe_3 <= product_phase4_5_pipe_2;
        end
      end
    end // temp_process21

  assign product_phase4_5 = product_phase4_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process22
      if (reset_x == 1'b0) begin
        product_phase4_6_pipe <= 0;
        product_phase4_6_pipe_1 <= 0;
        product_phase4_6_pipe_2 <= 0;
        product_phase4_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase4_6_pipe <= input_pipeline[2] * coeffphase4_6;

          product_phase4_6_pipe_1 <= product_phase4_6_pipe;
          product_phase4_6_pipe_2 <= product_phase4_6_pipe_1;
          product_phase4_6_pipe_3 <= product_phase4_6_pipe_2;
        end
      end
    end // temp_process22

  assign product_phase4_6 = product_phase4_6_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process23
      if (reset_x == 1'b0) begin
        product_phase5_1_pipe <= 0;
        product_phase5_1_pipe_1 <= 0;
        product_phase5_1_pipe_2 <= 0;
        product_phase5_1_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase5_1_pipe <= input_pipeline[3] * coeffphase5_1;

          product_phase5_1_pipe_1 <= product_phase5_1_pipe;
          product_phase5_1_pipe_2 <= product_phase5_1_pipe_1;
          product_phase5_1_pipe_3 <= product_phase5_1_pipe_2;
        end
      end
    end // temp_process23

  assign product_phase5_1 = product_phase5_1_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process24
      if (reset_x == 1'b0) begin
        product_phase5_2_pipe <= 0;
        product_phase5_2_pipe_1 <= 0;
        product_phase5_2_pipe_2 <= 0;
        product_phase5_2_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase5_2_pipe <= input_pipeline[3] * coeffphase5_2;

          product_phase5_2_pipe_1 <= product_phase5_2_pipe;
          product_phase5_2_pipe_2 <= product_phase5_2_pipe_1;
          product_phase5_2_pipe_3 <= product_phase5_2_pipe_2;
        end
      end
    end // temp_process24

  assign product_phase5_2 = product_phase5_2_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process25
      if (reset_x == 1'b0) begin
        product_phase5_3_pipe <= 0;
        product_phase5_3_pipe_1 <= 0;
        product_phase5_3_pipe_2 <= 0;
        product_phase5_3_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase5_3_pipe <= input_pipeline[3] * coeffphase5_3;

          product_phase5_3_pipe_1 <= product_phase5_3_pipe;
          product_phase5_3_pipe_2 <= product_phase5_3_pipe_1;
          product_phase5_3_pipe_3 <= product_phase5_3_pipe_2;
        end
      end
    end // temp_process25

  assign product_phase5_3 = product_phase5_3_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process26
      if (reset_x == 1'b0) begin
        product_phase5_4_pipe <= 0;
        product_phase5_4_pipe_1 <= 0;
        product_phase5_4_pipe_2 <= 0;
        product_phase5_4_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase5_4_pipe <= input_pipeline[3] * coeffphase5_4;

          product_phase5_4_pipe_1 <= product_phase5_4_pipe;
          product_phase5_4_pipe_2 <= product_phase5_4_pipe_1;
          product_phase5_4_pipe_3 <= product_phase5_4_pipe_2;
        end
      end
    end // temp_process26

  assign product_phase5_4 = product_phase5_4_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process27
      if (reset_x == 1'b0) begin
        product_phase5_5_pipe <= 0;
        product_phase5_5_pipe_1 <= 0;
        product_phase5_5_pipe_2 <= 0;
        product_phase5_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase5_5_pipe <= input_pipeline[3] * coeffphase5_5;

          product_phase5_5_pipe_1 <= product_phase5_5_pipe;
          product_phase5_5_pipe_2 <= product_phase5_5_pipe_1;
          product_phase5_5_pipe_3 <= product_phase5_5_pipe_2;
        end
      end
    end // temp_process27

  assign product_phase5_5 = product_phase5_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process28
      if (reset_x == 1'b0) begin
        product_phase5_6_pipe <= 0;
        product_phase5_6_pipe_1 <= 0;
        product_phase5_6_pipe_2 <= 0;
        product_phase5_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase5_6_pipe <= input_pipeline[3] * coeffphase5_6;

          product_phase5_6_pipe_1 <= product_phase5_6_pipe;
          product_phase5_6_pipe_2 <= product_phase5_6_pipe_1;
          product_phase5_6_pipe_3 <= product_phase5_6_pipe_2;
        end
      end
    end // temp_process28

  assign product_phase5_6 = product_phase5_6_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process29
      if (reset_x == 1'b0) begin
        product_phase6_4_pipe <= 0;
        product_phase6_4_pipe_1 <= 0;
        product_phase6_4_pipe_2 <= 0;
        product_phase6_4_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase6_4_pipe <= input_pipeline[4] * coeffphase6_4;

          product_phase6_4_pipe_1 <= product_phase6_4_pipe;
          product_phase6_4_pipe_2 <= product_phase6_4_pipe_1;
          product_phase6_4_pipe_3 <= product_phase6_4_pipe_2;
        end
      end
    end // temp_process29

  assign product_phase6_4 = product_phase6_4_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process30
      if (reset_x == 1'b0) begin
        product_phase6_5_pipe <= 0;
        product_phase6_5_pipe_1 <= 0;
        product_phase6_5_pipe_2 <= 0;
        product_phase6_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase6_5_pipe <= input_pipeline[4] * coeffphase6_5;

          product_phase6_5_pipe_1 <= product_phase6_5_pipe;
          product_phase6_5_pipe_2 <= product_phase6_5_pipe_1;
          product_phase6_5_pipe_3 <= product_phase6_5_pipe_2;
        end
      end
    end // temp_process30

  assign product_phase6_5 = product_phase6_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process31
      if (reset_x == 1'b0) begin
        product_phase6_6_pipe <= 0;
        product_phase6_6_pipe_1 <= 0;
        product_phase6_6_pipe_2 <= 0;
        product_phase6_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase6_6_pipe <= input_pipeline[4] * coeffphase6_6;

          product_phase6_6_pipe_1 <= product_phase6_6_pipe;
          product_phase6_6_pipe_2 <= product_phase6_6_pipe_1;
          product_phase6_6_pipe_3 <= product_phase6_6_pipe_2;
        end
      end
    end // temp_process31

  assign product_phase6_6 = product_phase6_6_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process32
      if (reset_x == 1'b0) begin
        product_phase7_1_pipe <= 0;
        product_phase7_1_pipe_1 <= 0;
        product_phase7_1_pipe_2 <= 0;
        product_phase7_1_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase7_1_pipe <= input_pipeline[5] * coeffphase7_1;

          product_phase7_1_pipe_1 <= product_phase7_1_pipe;
          product_phase7_1_pipe_2 <= product_phase7_1_pipe_1;
          product_phase7_1_pipe_3 <= product_phase7_1_pipe_2;
        end
      end
    end // temp_process32

  assign product_phase7_1 = product_phase7_1_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process33
      if (reset_x == 1'b0) begin
        product_phase7_2_pipe <= 0;
        product_phase7_2_pipe_1 <= 0;
        product_phase7_2_pipe_2 <= 0;
        product_phase7_2_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase7_2_pipe <= input_pipeline[5] * coeffphase7_2;

          product_phase7_2_pipe_1 <= product_phase7_2_pipe;
          product_phase7_2_pipe_2 <= product_phase7_2_pipe_1;
          product_phase7_2_pipe_3 <= product_phase7_2_pipe_2;
        end
      end
    end // temp_process33

  assign product_phase7_2 = product_phase7_2_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process34
      if (reset_x == 1'b0) begin
        product_phase7_3_pipe <= 0;
        product_phase7_3_pipe_1 <= 0;
        product_phase7_3_pipe_2 <= 0;
        product_phase7_3_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase7_3_pipe <= input_pipeline[5] * coeffphase7_3;

          product_phase7_3_pipe_1 <= product_phase7_3_pipe;
          product_phase7_3_pipe_2 <= product_phase7_3_pipe_1;
          product_phase7_3_pipe_3 <= product_phase7_3_pipe_2;
        end
      end
    end // temp_process34

  assign product_phase7_3 = product_phase7_3_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process35
      if (reset_x == 1'b0) begin
        product_phase7_4_pipe <= 0;
        product_phase7_4_pipe_1 <= 0;
        product_phase7_4_pipe_2 <= 0;
        product_phase7_4_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase7_4_pipe <= input_pipeline[5] * coeffphase7_4;

          product_phase7_4_pipe_1 <= product_phase7_4_pipe;
          product_phase7_4_pipe_2 <= product_phase7_4_pipe_1;
          product_phase7_4_pipe_3 <= product_phase7_4_pipe_2;
        end
      end
    end // temp_process35

  assign product_phase7_4 = product_phase7_4_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process36
      if (reset_x == 1'b0) begin
        product_phase7_5_pipe <= 0;
        product_phase7_5_pipe_1 <= 0;
        product_phase7_5_pipe_2 <= 0;
        product_phase7_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase7_5_pipe <= input_pipeline[5] * coeffphase7_5;

          product_phase7_5_pipe_1 <= product_phase7_5_pipe;
          product_phase7_5_pipe_2 <= product_phase7_5_pipe_1;
          product_phase7_5_pipe_3 <= product_phase7_5_pipe_2;
        end
      end
    end // temp_process36

  assign product_phase7_5 = product_phase7_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process37
      if (reset_x == 1'b0) begin
        product_phase7_6_pipe <= 0;
        product_phase7_6_pipe_1 <= 0;
        product_phase7_6_pipe_2 <= 0;
        product_phase7_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase7_6_pipe <= input_pipeline[5] * coeffphase7_6;

          product_phase7_6_pipe_1 <= product_phase7_6_pipe;
          product_phase7_6_pipe_2 <= product_phase7_6_pipe_1;
          product_phase7_6_pipe_3 <= product_phase7_6_pipe_2;
        end
      end
    end // temp_process37

  assign product_phase7_6 = product_phase7_6_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process38
      if (reset_x == 1'b0) begin
        product_phase8_1_pipe <= 0;
        product_phase8_1_pipe_1 <= 0;
        product_phase8_1_pipe_2 <= 0;
        product_phase8_1_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase8_1_pipe <= input_pipeline[6] * coeffphase8_1;

          product_phase8_1_pipe_1 <= product_phase8_1_pipe;
          product_phase8_1_pipe_2 <= product_phase8_1_pipe_1;
          product_phase8_1_pipe_3 <= product_phase8_1_pipe_2;
        end
      end
    end // temp_process38

  assign product_phase8_1 = product_phase8_1_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process39
      if (reset_x == 1'b0) begin
        product_phase8_2_pipe <= 0;
        product_phase8_2_pipe_1 <= 0;
        product_phase8_2_pipe_2 <= 0;
        product_phase8_2_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase8_2_pipe <= input_pipeline[6] * coeffphase8_2;

          product_phase8_2_pipe_1 <= product_phase8_2_pipe;
          product_phase8_2_pipe_2 <= product_phase8_2_pipe_1;
          product_phase8_2_pipe_3 <= product_phase8_2_pipe_2;
        end
      end
    end // temp_process39

  assign product_phase8_2 = product_phase8_2_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process40
      if (reset_x == 1'b0) begin
        product_phase8_3_pipe <= 0;
        product_phase8_3_pipe_1 <= 0;
        product_phase8_3_pipe_2 <= 0;
        product_phase8_3_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase8_3_pipe <= input_pipeline[6] * coeffphase8_3;

          product_phase8_3_pipe_1 <= product_phase8_3_pipe;
          product_phase8_3_pipe_2 <= product_phase8_3_pipe_1;
          product_phase8_3_pipe_3 <= product_phase8_3_pipe_2;
        end
      end
    end // temp_process40

  assign product_phase8_3 = product_phase8_3_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process41
      if (reset_x == 1'b0) begin
        product_phase8_4_pipe <= 0;
        product_phase8_4_pipe_1 <= 0;
        product_phase8_4_pipe_2 <= 0;
        product_phase8_4_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase8_4_pipe <= input_pipeline[6] * coeffphase8_4;

          product_phase8_4_pipe_1 <= product_phase8_4_pipe;
          product_phase8_4_pipe_2 <= product_phase8_4_pipe_1;
          product_phase8_4_pipe_3 <= product_phase8_4_pipe_2;
        end
      end
    end // temp_process41

  assign product_phase8_4 = product_phase8_4_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process42
      if (reset_x == 1'b0) begin
        product_phase8_5_pipe <= 0;
        product_phase8_5_pipe_1 <= 0;
        product_phase8_5_pipe_2 <= 0;
        product_phase8_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase8_5_pipe <= input_pipeline[6] * coeffphase8_5;

          product_phase8_5_pipe_1 <= product_phase8_5_pipe;
          product_phase8_5_pipe_2 <= product_phase8_5_pipe_1;
          product_phase8_5_pipe_3 <= product_phase8_5_pipe_2;
        end
      end
    end // temp_process42

  assign product_phase8_5 = product_phase8_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process43
      if (reset_x == 1'b0) begin
        product_phase8_6_pipe <= 0;
        product_phase8_6_pipe_1 <= 0;
        product_phase8_6_pipe_2 <= 0;
        product_phase8_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase8_6_pipe <= input_pipeline[6] * coeffphase8_6;

          product_phase8_6_pipe_1 <= product_phase8_6_pipe;
          product_phase8_6_pipe_2 <= product_phase8_6_pipe_1;
          product_phase8_6_pipe_3 <= product_phase8_6_pipe_2;
        end
      end
    end // temp_process43

  assign product_phase8_6 = product_phase8_6_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process44
      if (reset_x == 1'b0) begin
        product_phase9_1_pipe <= 0;
        product_phase9_1_pipe_1 <= 0;
        product_phase9_1_pipe_2 <= 0;
        product_phase9_1_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase9_1_pipe <= input_pipeline[7] * coeffphase9_1;

          product_phase9_1_pipe_1 <= product_phase9_1_pipe;
          product_phase9_1_pipe_2 <= product_phase9_1_pipe_1;
          product_phase9_1_pipe_3 <= product_phase9_1_pipe_2;
        end
      end
    end // temp_process44

  assign product_phase9_1 = product_phase9_1_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process45
      if (reset_x == 1'b0) begin
        product_phase9_2_pipe <= 0;
        product_phase9_2_pipe_1 <= 0;
        product_phase9_2_pipe_2 <= 0;
        product_phase9_2_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase9_2_pipe <= input_pipeline[7] * coeffphase9_2;

          product_phase9_2_pipe_1 <= product_phase9_2_pipe;
          product_phase9_2_pipe_2 <= product_phase9_2_pipe_1;
          product_phase9_2_pipe_3 <= product_phase9_2_pipe_2;
        end
      end
    end // temp_process45

  assign product_phase9_2 = product_phase9_2_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process46
      if (reset_x == 1'b0) begin
        product_phase9_3_pipe <= 0;
        product_phase9_3_pipe_1 <= 0;
        product_phase9_3_pipe_2 <= 0;
        product_phase9_3_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase9_3_pipe <= input_pipeline[7] * coeffphase9_3;

          product_phase9_3_pipe_1 <= product_phase9_3_pipe;
          product_phase9_3_pipe_2 <= product_phase9_3_pipe_1;
          product_phase9_3_pipe_3 <= product_phase9_3_pipe_2;
        end
      end
    end // temp_process46

  assign product_phase9_3 = product_phase9_3_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process47
      if (reset_x == 1'b0) begin
        product_phase9_4_pipe <= 0;
        product_phase9_4_pipe_1 <= 0;
        product_phase9_4_pipe_2 <= 0;
        product_phase9_4_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase9_4_pipe <= input_pipeline[7] * coeffphase9_4;

          product_phase9_4_pipe_1 <= product_phase9_4_pipe;
          product_phase9_4_pipe_2 <= product_phase9_4_pipe_1;
          product_phase9_4_pipe_3 <= product_phase9_4_pipe_2;
        end
      end
    end // temp_process47

  assign product_phase9_4 = product_phase9_4_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process48
      if (reset_x == 1'b0) begin
        product_phase9_5_pipe <= 0;
        product_phase9_5_pipe_1 <= 0;
        product_phase9_5_pipe_2 <= 0;
        product_phase9_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase9_5_pipe <= input_pipeline[7] * coeffphase9_5;

          product_phase9_5_pipe_1 <= product_phase9_5_pipe;
          product_phase9_5_pipe_2 <= product_phase9_5_pipe_1;
          product_phase9_5_pipe_3 <= product_phase9_5_pipe_2;
        end
      end
    end // temp_process48

  assign product_phase9_5 = product_phase9_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process49
      if (reset_x == 1'b0) begin
        product_phase9_6_pipe <= 0;
        product_phase9_6_pipe_1 <= 0;
        product_phase9_6_pipe_2 <= 0;
        product_phase9_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase9_6_pipe <= input_pipeline[7] * coeffphase9_6;

          product_phase9_6_pipe_1 <= product_phase9_6_pipe;
          product_phase9_6_pipe_2 <= product_phase9_6_pipe_1;
          product_phase9_6_pipe_3 <= product_phase9_6_pipe_2;
        end
      end
    end // temp_process49

  assign product_phase9_6 = product_phase9_6_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process50
      if (reset_x == 1'b0) begin
        product_phase10_1_pipe <= 0;
        product_phase10_1_pipe_1 <= 0;
        product_phase10_1_pipe_2 <= 0;
        product_phase10_1_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase10_1_pipe <= input_pipeline[8] * coeffphase10_1;

          product_phase10_1_pipe_1 <= product_phase10_1_pipe;
          product_phase10_1_pipe_2 <= product_phase10_1_pipe_1;
          product_phase10_1_pipe_3 <= product_phase10_1_pipe_2;
        end
      end
    end // temp_process50

  assign product_phase10_1 = product_phase10_1_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process51
      if (reset_x == 1'b0) begin
        product_phase10_2_pipe <= 0;
        product_phase10_2_pipe_1 <= 0;
        product_phase10_2_pipe_2 <= 0;
        product_phase10_2_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase10_2_pipe <= input_pipeline[8] * coeffphase10_2;

          product_phase10_2_pipe_1 <= product_phase10_2_pipe;
          product_phase10_2_pipe_2 <= product_phase10_2_pipe_1;
          product_phase10_2_pipe_3 <= product_phase10_2_pipe_2;
        end
      end
    end // temp_process51

  assign product_phase10_2 = product_phase10_2_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process52
      if (reset_x == 1'b0) begin
        product_phase10_3_pipe <= 0;
        product_phase10_3_pipe_1 <= 0;
        product_phase10_3_pipe_2 <= 0;
        product_phase10_3_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase10_3_pipe <= input_pipeline[8] * coeffphase10_3;

          product_phase10_3_pipe_1 <= product_phase10_3_pipe;
          product_phase10_3_pipe_2 <= product_phase10_3_pipe_1;
          product_phase10_3_pipe_3 <= product_phase10_3_pipe_2;
        end
      end
    end // temp_process52

  assign product_phase10_3 = product_phase10_3_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process53
      if (reset_x == 1'b0) begin
        product_phase10_4_pipe <= 0;
        product_phase10_4_pipe_1 <= 0;
        product_phase10_4_pipe_2 <= 0;
        product_phase10_4_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase10_4_pipe <= input_pipeline[8] * coeffphase10_4;

          product_phase10_4_pipe_1 <= product_phase10_4_pipe;
          product_phase10_4_pipe_2 <= product_phase10_4_pipe_1;
          product_phase10_4_pipe_3 <= product_phase10_4_pipe_2;
        end
      end
    end // temp_process53

  assign product_phase10_4 = product_phase10_4_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process54
      if (reset_x == 1'b0) begin
        product_phase10_5_pipe <= 0;
        product_phase10_5_pipe_1 <= 0;
        product_phase10_5_pipe_2 <= 0;
        product_phase10_5_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase10_5_pipe <= input_pipeline[8] * coeffphase10_5;

          product_phase10_5_pipe_1 <= product_phase10_5_pipe;
          product_phase10_5_pipe_2 <= product_phase10_5_pipe_1;
          product_phase10_5_pipe_3 <= product_phase10_5_pipe_2;
        end
      end
    end // temp_process54

  assign product_phase10_5 = product_phase10_5_pipe_3;

  always @ (posedge sys_clk)
    begin: temp_process55
      if (reset_x == 1'b0) begin
        product_phase10_6_pipe <= 0;
        product_phase10_6_pipe_1 <= 0;
        product_phase10_6_pipe_2 <= 0;
        product_phase10_6_pipe_3 <= 0;
      end
      else begin
        if (enb_1_1_1 == 1'b1) begin

          product_phase10_6_pipe <= input_pipeline[8] * coeffphase10_6;

          product_phase10_6_pipe_1 <= product_phase10_6_pipe;
          product_phase10_6_pipe_2 <= product_phase10_6_pipe_1;
          product_phase10_6_pipe_3 <= product_phase10_6_pipe_2;
        end
      end
    end // temp_process55

  assign product_phase10_6 = product_phase10_6_pipe_3;

  assign add_cast = $signed({{3{product_phase1_7[31]}}, product_phase1_7});
  assign add_cast_1 = $signed({{3{product_phase2_1[31]}}, product_phase2_1});
  assign add_temp = add_cast + add_cast_1;
  assign polyadd_1 = add_temp[34:0];

  assign add_cast_2 = polyadd_1;
  assign add_cast_3 = $signed({{3{product_phase3_1[31]}}, product_phase3_1});
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign polyadd_1_1 = add_temp_1[34:0];

  assign add_cast_4 = polyadd_1_1;
  assign add_cast_5 = $signed({{3{product_phase4_1[31]}}, product_phase4_1});
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign polyadd_1_2 = add_temp_2[34:0];

  assign add_cast_6 = polyadd_1_2;
  assign add_cast_7 = $signed({{3{product_phase5_1[31]}}, product_phase5_1});
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign polyadd_1_3 = add_temp_3[34:0];

  assign add_cast_8 = polyadd_1_3;
  assign add_cast_9 = $signed({{3{product_phase6_6[31]}}, product_phase6_6});
  assign add_temp_4 = add_cast_8 + add_cast_9;
  assign polyadd_1_4 = add_temp_4[34:0];

  assign add_cast_10 = polyadd_1_4;
  assign add_cast_11 = $signed({{3{product_phase7_1[31]}}, product_phase7_1});
  assign add_temp_5 = add_cast_10 + add_cast_11;
  assign polyadd_1_5 = add_temp_5[34:0];

  assign add_cast_12 = polyadd_1_5;
  assign add_cast_13 = $signed({{3{product_phase8_1[31]}}, product_phase8_1});
  assign add_temp_6 = add_cast_12 + add_cast_13;
  assign polyadd_1_6 = add_temp_6[34:0];

  assign add_cast_14 = polyadd_1_6;
  assign add_cast_15 = $signed({{3{product_phase9_1[31]}}, product_phase9_1});
  assign add_temp_7 = add_cast_14 + add_cast_15;
  assign polyadd_1_7 = add_temp_7[34:0];

  assign add_cast_16 = polyadd_1_7;
  assign add_cast_17 = $signed({{3{product_phase10_1[31]}}, product_phase10_1});
  assign add_temp_8 = add_cast_16 + add_cast_17;
  assign polyadd_1_8 = add_temp_8[34:0];

  assign add_cast_18 = $signed({{3{product_phase1_6[31]}}, product_phase1_6});
  assign add_cast_19 = $signed({{3{product_phase2_2[31]}}, product_phase2_2});
  assign add_temp_9 = add_cast_18 + add_cast_19;
  assign polyadd_2 = add_temp_9[34:0];

  assign add_cast_20 = polyadd_2;
  assign add_cast_21 = $signed({{3{product_phase3_2[31]}}, product_phase3_2});
  assign add_temp_10 = add_cast_20 + add_cast_21;
  assign polyadd_2_1 = add_temp_10[34:0];

  assign add_cast_22 = polyadd_2_1;
  assign add_cast_23 = $signed({{3{product_phase4_2[31]}}, product_phase4_2});
  assign add_temp_11 = add_cast_22 + add_cast_23;
  assign polyadd_2_2 = add_temp_11[34:0];

  assign add_cast_24 = polyadd_2_2;
  assign add_cast_25 = $signed({{3{product_phase5_2[31]}}, product_phase5_2});
  assign add_temp_12 = add_cast_24 + add_cast_25;
  assign polyadd_2_3 = add_temp_12[34:0];

  assign add_cast_26 = polyadd_2_3;
  assign add_cast_27 = $signed({{3{product_phase6_5[31]}}, product_phase6_5});
  assign add_temp_13 = add_cast_26 + add_cast_27;
  assign polyadd_2_4 = add_temp_13[34:0];

  assign add_cast_28 = polyadd_2_4;
  assign add_cast_29 = $signed({{3{product_phase7_2[31]}}, product_phase7_2});
  assign add_temp_14 = add_cast_28 + add_cast_29;
  assign polyadd_2_5 = add_temp_14[34:0];

  assign add_cast_30 = polyadd_2_5;
  assign add_cast_31 = $signed({{3{product_phase8_2[31]}}, product_phase8_2});
  assign add_temp_15 = add_cast_30 + add_cast_31;
  assign polyadd_2_6 = add_temp_15[34:0];

  assign add_cast_32 = polyadd_2_6;
  assign add_cast_33 = $signed({{3{product_phase9_2[31]}}, product_phase9_2});
  assign add_temp_16 = add_cast_32 + add_cast_33;
  assign polyadd_2_7 = add_temp_16[34:0];

  assign add_cast_34 = polyadd_2_7;
  assign add_cast_35 = $signed({{3{product_phase10_2[31]}}, product_phase10_2});
  assign add_temp_17 = add_cast_34 + add_cast_35;
  assign polyadd_2_8 = add_temp_17[34:0];

  assign add_cast_36 = $signed({{3{product_phase1_5[31]}}, product_phase1_5});
  assign add_cast_37 = $signed({{3{product_phase2_3[31]}}, product_phase2_3});
  assign add_temp_18 = add_cast_36 + add_cast_37;
  assign polyadd_3 = add_temp_18[34:0];

  assign add_cast_38 = polyadd_3;
  assign add_cast_39 = $signed({{3{product_phase3_3[31]}}, product_phase3_3});
  assign add_temp_19 = add_cast_38 + add_cast_39;
  assign polyadd_3_1 = add_temp_19[34:0];

  assign add_cast_40 = polyadd_3_1;
  assign add_cast_41 = $signed({{3{product_phase4_3[31]}}, product_phase4_3});
  assign add_temp_20 = add_cast_40 + add_cast_41;
  assign polyadd_3_2 = add_temp_20[34:0];

  assign add_cast_42 = polyadd_3_2;
  assign add_cast_43 = $signed({{3{product_phase5_3[31]}}, product_phase5_3});
  assign add_temp_21 = add_cast_42 + add_cast_43;
  assign polyadd_3_3 = add_temp_21[34:0];

  assign add_cast_44 = polyadd_3_3;
  assign add_cast_45 = $signed({{3{product_phase6_4[31]}}, product_phase6_4});
  assign add_temp_22 = add_cast_44 + add_cast_45;
  assign polyadd_3_4 = add_temp_22[34:0];

  assign add_cast_46 = polyadd_3_4;
  assign add_cast_47 = $signed({{3{product_phase7_3[31]}}, product_phase7_3});
  assign add_temp_23 = add_cast_46 + add_cast_47;
  assign polyadd_3_5 = add_temp_23[34:0];

  assign add_cast_48 = polyadd_3_5;
  assign add_cast_49 = $signed({{3{product_phase8_3[31]}}, product_phase8_3});
  assign add_temp_24 = add_cast_48 + add_cast_49;
  assign polyadd_3_6 = add_temp_24[34:0];

  assign add_cast_50 = polyadd_3_6;
  assign add_cast_51 = $signed({{3{product_phase9_3[31]}}, product_phase9_3});
  assign add_temp_25 = add_cast_50 + add_cast_51;
  assign polyadd_3_7 = add_temp_25[34:0];

  assign add_cast_52 = polyadd_3_7;
  assign add_cast_53 = $signed({{3{product_phase10_3[31]}}, product_phase10_3});
  assign add_temp_26 = add_cast_52 + add_cast_53;
  assign polyadd_3_8 = add_temp_26[34:0];

  assign add_cast_54 = $signed({{3{product_phase1_4[31]}}, product_phase1_4});
  assign add_cast_55 = $signed({{3{product_phase2_4[31]}}, product_phase2_4});
  assign add_temp_27 = add_cast_54 + add_cast_55;
  assign polyadd_4 = add_temp_27[34:0];

  assign add_cast_56 = polyadd_4;
  assign add_cast_57 = $signed({{3{product_phase3_4[31]}}, product_phase3_4});
  assign add_temp_28 = add_cast_56 + add_cast_57;
  assign polyadd_4_1 = add_temp_28[34:0];

  assign add_cast_58 = polyadd_4_1;
  assign add_cast_59 = $signed({{3{product_phase4_4[31]}}, product_phase4_4});
  assign add_temp_29 = add_cast_58 + add_cast_59;
  assign polyadd_4_2 = add_temp_29[34:0];

  assign add_cast_60 = polyadd_4_2;
  assign add_cast_61 = $signed({{3{product_phase5_4[31]}}, product_phase5_4});
  assign add_temp_30 = add_cast_60 + add_cast_61;
  assign polyadd_4_3 = add_temp_30[34:0];

  assign add_cast_62 = polyadd_4_3;
  assign add_cast_63 = $signed({{3{product_phase6_4[31]}}, product_phase6_4});
  assign add_temp_31 = add_cast_62 + add_cast_63;
  assign polyadd_4_4 = add_temp_31[34:0];

  assign add_cast_64 = polyadd_4_4;
  assign add_cast_65 = $signed({{3{product_phase7_4[31]}}, product_phase7_4});
  assign add_temp_32 = add_cast_64 + add_cast_65;
  assign polyadd_4_5 = add_temp_32[34:0];

  assign add_cast_66 = polyadd_4_5;
  assign add_cast_67 = $signed({{3{product_phase8_4[31]}}, product_phase8_4});
  assign add_temp_33 = add_cast_66 + add_cast_67;
  assign polyadd_4_6 = add_temp_33[34:0];

  assign add_cast_68 = polyadd_4_6;
  assign add_cast_69 = $signed({{3{product_phase9_4[31]}}, product_phase9_4});
  assign add_temp_34 = add_cast_68 + add_cast_69;
  assign polyadd_4_7 = add_temp_34[34:0];

  assign add_cast_70 = polyadd_4_7;
  assign add_cast_71 = $signed({{3{product_phase10_4[31]}}, product_phase10_4});
  assign add_temp_35 = add_cast_70 + add_cast_71;
  assign polyadd_4_8 = add_temp_35[34:0];

  assign add_cast_72 = $signed({{3{product_phase1_5[31]}}, product_phase1_5});
  assign add_cast_73 = $signed({{3{product_phase2_5[31]}}, product_phase2_5});
  assign add_temp_36 = add_cast_72 + add_cast_73;
  assign polyadd_5 = add_temp_36[34:0];

  assign add_cast_74 = polyadd_5;
  assign add_cast_75 = $signed({{3{product_phase3_5[31]}}, product_phase3_5});
  assign add_temp_37 = add_cast_74 + add_cast_75;
  assign polyadd_5_1 = add_temp_37[34:0];

  assign add_cast_76 = polyadd_5_1;
  assign add_cast_77 = $signed({{3{product_phase4_5[31]}}, product_phase4_5});
  assign add_temp_38 = add_cast_76 + add_cast_77;
  assign polyadd_5_2 = add_temp_38[34:0];

  assign add_cast_78 = polyadd_5_2;
  assign add_cast_79 = $signed({{3{product_phase5_5[31]}}, product_phase5_5});
  assign add_temp_39 = add_cast_78 + add_cast_79;
  assign polyadd_5_3 = add_temp_39[34:0];

  assign add_cast_80 = polyadd_5_3;
  assign add_cast_81 = $signed({{3{product_phase6_5[31]}}, product_phase6_5});
  assign add_temp_40 = add_cast_80 + add_cast_81;
  assign polyadd_5_4 = add_temp_40[34:0];

  assign add_cast_82 = polyadd_5_4;
  assign add_cast_83 = $signed({{3{product_phase7_5[31]}}, product_phase7_5});
  assign add_temp_41 = add_cast_82 + add_cast_83;
  assign polyadd_5_5 = add_temp_41[34:0];

  assign add_cast_84 = polyadd_5_5;
  assign add_cast_85 = $signed({{3{product_phase8_5[31]}}, product_phase8_5});
  assign add_temp_42 = add_cast_84 + add_cast_85;
  assign polyadd_5_6 = add_temp_42[34:0];

  assign add_cast_86 = polyadd_5_6;
  assign add_cast_87 = $signed({{3{product_phase9_5[31]}}, product_phase9_5});
  assign add_temp_43 = add_cast_86 + add_cast_87;
  assign polyadd_5_7 = add_temp_43[34:0];

  assign add_cast_88 = polyadd_5_7;
  assign add_cast_89 = $signed({{3{product_phase10_5[31]}}, product_phase10_5});
  assign add_temp_44 = add_cast_88 + add_cast_89;
  assign polyadd_5_8 = add_temp_44[34:0];

  assign add_cast_90 = $signed({{3{product_phase1_6[31]}}, product_phase1_6});
  assign add_cast_91 = $signed({{3{product_phase2_6[31]}}, product_phase2_6});
  assign add_temp_45 = add_cast_90 + add_cast_91;
  assign polyadd_6 = add_temp_45[34:0];

  assign add_cast_92 = polyadd_6;
  assign add_cast_93 = $signed({{3{product_phase3_6[31]}}, product_phase3_6});
  assign add_temp_46 = add_cast_92 + add_cast_93;
  assign polyadd_6_1 = add_temp_46[34:0];

  assign add_cast_94 = polyadd_6_1;
  assign add_cast_95 = $signed({{3{product_phase4_6[31]}}, product_phase4_6});
  assign add_temp_47 = add_cast_94 + add_cast_95;
  assign polyadd_6_2 = add_temp_47[34:0];

  assign add_cast_96 = polyadd_6_2;
  assign add_cast_97 = $signed({{3{product_phase5_6[31]}}, product_phase5_6});
  assign add_temp_48 = add_cast_96 + add_cast_97;
  assign polyadd_6_3 = add_temp_48[34:0];

  assign add_cast_98 = polyadd_6_3;
  assign add_cast_99 = $signed({{3{product_phase6_6[31]}}, product_phase6_6});
  assign add_temp_49 = add_cast_98 + add_cast_99;
  assign polyadd_6_4 = add_temp_49[34:0];

  assign add_cast_100 = polyadd_6_4;
  assign add_cast_101 = $signed({{3{product_phase7_6[31]}}, product_phase7_6});
  assign add_temp_50 = add_cast_100 + add_cast_101;
  assign polyadd_6_5 = add_temp_50[34:0];

  assign add_cast_102 = polyadd_6_5;
  assign add_cast_103 = $signed({{3{product_phase8_6[31]}}, product_phase8_6});
  assign add_temp_51 = add_cast_102 + add_cast_103;
  assign polyadd_6_6 = add_temp_51[34:0];

  assign add_cast_104 = polyadd_6_6;
  assign add_cast_105 = $signed({{3{product_phase9_6[31]}}, product_phase9_6});
  assign add_temp_52 = add_cast_104 + add_cast_105;
  assign polyadd_6_7 = add_temp_52[34:0];

  assign add_cast_106 = polyadd_6_7;
  assign add_cast_107 = $signed({{3{product_phase10_6[31]}}, product_phase10_6});
  assign add_temp_53 = add_cast_106 + add_cast_107;
  assign polyadd_6_8 = add_temp_53[34:0];

  assign polyadd_7 = $signed({{3{product_phase1_7[31]}}, product_phase1_7});

  always @ ( posedge sys_clk)
    begin: Delay_Pipeline_process
      if (reset_x == 1'b0) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
      end
      else begin
        if (phase_4 == 1'b1) begin
          delay_pipeline[0] <= sumvector[0];
          delay_pipeline[1] <= sumvector[1];
          delay_pipeline[2] <= sumvector[2];
          delay_pipeline[3] <= sumvector[3];
          delay_pipeline[4] <= sumvector[4];
          delay_pipeline[5] <= sumvector[5];
        end
      end
    end // Delay_Pipeline_process

  assign add_cast_108 = polyadd_1_8;
  assign add_cast_109 = delay_pipeline[0];
  assign add_temp_54 = add_cast_108 + add_cast_109;
  assign finalsum = add_temp_54[34:0];

  assign add_cast_110 = polyadd_2_8;
  assign add_cast_111 = delay_pipeline[1];
  assign add_temp_55 = add_cast_110 + add_cast_111;
  assign sumvector[0] = add_temp_55[34:0];

  assign add_cast_112 = polyadd_3_8;
  assign add_cast_113 = delay_pipeline[2];
  assign add_temp_56 = add_cast_112 + add_cast_113;
  assign sumvector[1] = add_temp_56[34:0];

  assign add_cast_114 = polyadd_4_8;
  assign add_cast_115 = delay_pipeline[3];
  assign add_temp_57 = add_cast_114 + add_cast_115;
  assign sumvector[2] = add_temp_57[34:0];

  assign add_cast_116 = polyadd_5_8;
  assign add_cast_117 = delay_pipeline[4];
  assign add_temp_58 = add_cast_116 + add_cast_117;
  assign sumvector[3] = add_temp_58[34:0];

  assign add_cast_118 = polyadd_6_8;
  assign add_cast_119 = delay_pipeline[5];
  assign add_temp_59 = add_cast_118 + add_cast_119;
  assign sumvector[4] = add_temp_59[34:0];

  assign sumvector[5] = polyadd_7;

  assign output_typeconvert = finalsum[31:0];

  always @ ( posedge sys_clk)
    begin: DataHoldRegister_process
      if (reset_x == 1'b0) begin
        regout <= 0;
      end
      else begin
        if (phase_4 == 1'b1) begin
          regout <= output_typeconvert;
        end
      end
    end // DataHoldRegister_process

  assign muxout = (phase_4 == 1'b1) ? output_typeconvert :
            regout;
  // Assignment Statements
  assign FIR_Decimation_out = muxout;
endmodule  // FIR_Decimation
