// -------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_polyphase\fir_ds10_polyphase.v
// Created: 2026-01-07 16:23:38
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-08
// Target subsystem base rate: 1e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-07
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// o_fir_data                    ce_out        1e-07
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fir_ds10_polyphase
// Source Path: fir_ds10_polyphase
// Hierarchy Level: 0
// Model version: 2.0
// 
// -------------------------------------------------------------
module fir_ds10_polyphase
          (sys_clk,
           reset_x,
           sys_clk_en,
           i_adc_data,
           ce_out,
           o_fir_data);


  input   sys_clk;
  input   reset_x;
  input   sys_clk_en;
  input   signed [15:0] i_adc_data;  // sfix16_En14
  output  ce_out;
  output  signed [15:0] o_fir_data;  // sfix16_En14


  wire enb_1_1_1;
  wire enb_1_10_1;
  wire signed [31:0] FIR_Decimation_out1;  // sfix32_En28
  wire [15:0] Bit_Slice_out1;  // uint16
  wire signed [15:0] Data_Type_Conversion1_out1;  // sfix16_En14


  fir_ds10_polyphase_tc u_fir_ds10_polyphase_tc (.sys_clk(sys_clk),
                                                 .reset_x(reset_x),
                                                 .sys_clk_en(sys_clk_en),
                                                 .enb_1_1_1(enb_1_1_1),
                                                 .enb_1_10_1(enb_1_10_1)
                                                 );

  FIR_Decimation u_FIR_Decimation (.sys_clk(sys_clk),
                                   .enb_1_1_1(enb_1_1_1),
                                   .reset_x(reset_x),
                                   .FIR_Decimation_in(i_adc_data),  // sfix16_En14
                                   .FIR_Decimation_out(FIR_Decimation_out1)  // sfix32_En28
                                   );

  assign Bit_Slice_out1 = FIR_Decimation_out1[29:14];



  assign Data_Type_Conversion1_out1 = Bit_Slice_out1;



  assign o_fir_data = Data_Type_Conversion1_out1;

  assign ce_out = enb_1_10_1;

endmodule  // fir_ds10_polyphase

