// -------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_onephase\Discrete_FIR_Filter.v
// Created: 2026-01-24 16:18:43
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Discrete_FIR_Filter
// Source Path: fir_ds10_onephase/Discrete FIR Filter
// Hierarchy Level: 1
// Model version: 2.1
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------
module Discrete_FIR_Filter
          (sys_clk,
           reset_x,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   sys_clk;
  input   reset_x;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En14
  input   validIn;
  output  signed [33:0] dataOut;  // sfix34_En28
  output  validOut;


  wire syncReset;


  assign syncReset = 1'b0;



  Filter u_FilterBank (.sys_clk(sys_clk),
                       .reset_x(reset_x),
                       .enb(enb),
                       .dataIn(dataIn),  // sfix16_En14
                       .validIn(validIn),
                       .syncReset(syncReset),
                       .dataOut(dataOut),  // sfix34_En28
                       .validOut(validOut)
                       );

endmodule  // Discrete_FIR_Filter

