// -------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_onephase\FilterTapWMultOutCSD.v
// Created: 2026-01-24 16:18:43
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapWMultOutCSD
// Source Path: fir_ds10_onephase/Discrete FIR Filter/Filter/subFilter/FilterTapWMultOutCSD
// Hierarchy Level: 4
// Model version: 2.1
// 
// -------------------------------------------------------------
module FilterTapWMultOutCSD
          (sys_clk,
           enb,
           dinReg2_0_re,
           addin,
           multVld,
           syncReset,
           tapout,
           multOut);


  input   sys_clk;
  input   enb;
  input   signed [15:0] dinReg2_0_re;  // sfix16_En14
  input   signed [33:0] addin;  // sfix34_En28
  input   multVld;
  input   syncReset;
  output  signed [33:0] tapout;  // sfix34_En28
  output  signed [33:0] multOut;  // sfix34_En28


  reg signed [15:0] multIn;  // sfix16_En14
  wire signed [31:0] gain_1;  // sfix32
  wire signed [31:0] gain_2;  // sfix32
  wire signed [31:0] gain_3;  // sfix32
  wire signed [31:0] gain_4;  // sfix32
  wire signed [31:0] gain_5;  // sfix32
  wire signed [31:0] multIn_1;  // sfix32_En28
  reg signed [15:0] fTap_din_reg;  // sfix16
  reg signed [31:0] fTap_mult_reg;  // sfix32
  reg signed [33:0] fTap_addout_reg;  // sfix34
  reg signed [15:0] fTap_din_reg_next;  // sfix16_En14
  reg signed [31:0] fTap_mult_reg_next;  // sfix32_En28
  reg signed [33:0] fTap_addout_reg_next;  // sfix34_En28
  reg signed [33:0] multOut_1;  // sfix34_En28
  reg signed [33:0] tapout_1;  // sfix34_En28
  reg signed [33:0] fTap_mult_cast;  // sfix34_En28

  initial begin
    fTap_din_reg = 16'sb0000000000000000;
    fTap_mult_reg = 32'sb00000000000000000000000000000000;
    fTap_addout_reg = 34'sh000000000;
  end

  // CSD Encoding (358) : 0101100110; Cost (Adders) = 4
  assign gain_1 = {{8{multIn[15]}}, {multIn, 8'b00000000}};
  assign gain_2 = {{10{multIn[15]}}, {multIn, 6'b000000}};
  assign gain_3 = {{11{multIn[15]}}, {multIn, 5'b00000}};
  assign gain_4 = {{14{multIn[15]}}, {multIn, 2'b00}};
  assign gain_5 = {{15{multIn[15]}}, {multIn, 1'b0}};
  assign multIn_1 =  - ((((gain_1 + gain_2) + gain_3) + gain_4) + gain_5);



  // FilterTapWMultOutCSD
  always @(posedge sys_clk)
    begin : fTap_process
      if (enb) begin
        if (syncReset == 1'b1) begin
          fTap_din_reg <= 16'sb0000000000000000;
          fTap_mult_reg <= 32'sb00000000000000000000000000000000;
          fTap_addout_reg <= 34'sh000000000;
        end
        else begin
          fTap_din_reg <= fTap_din_reg_next;
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
        end
      end
    end

  always @(addin, dinReg2_0_re, fTap_addout_reg, fTap_din_reg, fTap_mult_reg, multIn_1,
       multVld) begin
    fTap_addout_reg_next = fTap_addout_reg;
    fTap_mult_cast = {{2{fTap_mult_reg[31]}}, fTap_mult_reg};
    if (multVld) begin
      fTap_addout_reg_next = fTap_mult_cast + addin;
    end
    fTap_mult_reg_next = multIn_1;
    fTap_din_reg_next = dinReg2_0_re;
    multIn = fTap_din_reg;
    multOut_1 = fTap_mult_cast;
    tapout_1 = fTap_addout_reg;
  end



  assign tapout = tapout_1;

  assign multOut = multOut_1;

endmodule  // FilterTapWMultOutCSD

