// -------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_onephase\Filter.v
// Created: 2026-01-24 16:18:43
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter
// Source Path: fir_ds10_onephase/Discrete FIR Filter/Filter
// Hierarchy Level: 2
// Model version: 2.1
// 
// -------------------------------------------------------------
module Filter
          (sys_clk,
           reset_x,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut,
           validOut);


  input   sys_clk;
  input   reset_x;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En14
  input   validIn;
  input   syncReset;
  output  signed [33:0] dataOut;  // sfix34_En28
  output  validOut;


  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En14
  reg signed [15:0] dinReg2_0_re;  // sfix16_En14
  reg  dinReg2Vld;
  wire signed [33:0] dout_1_re;  // sfix34_En28
  wire doutVld;


  always @(posedge sys_clk)
    begin : intdelay_process
      if (reset_x == 1'b0) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end



  always @(posedge sys_clk)
    begin : intdelay_1_process
      if (reset_x == 1'b0) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn;
            end
          end
        end
      end
    end



  always @(posedge sys_clk)
    begin : intdelay_2_process
      if (reset_x == 1'b0) begin
        dinReg2_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end



  always @(posedge sys_clk)
    begin : intdelay_3_process
      if (reset_x == 1'b0) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end



  subFilter u_subFilter_1_re (.sys_clk(sys_clk),
                              .reset_x(reset_x),
                              .enb(enb),
                              .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                              .dinRegVld(dinReg2Vld),
                              .syncReset(syncReset),
                              .dout_1_re(dout_1_re),  // sfix34_En28
                              .doutVld(doutVld)
                              );

  assign dataOut = dout_1_re;

  assign validOut = doutVld;

endmodule  // Filter

