// -------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_onephase\FilterTapWvldIn.v
// Created: 2026-01-24 16:18:43
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapWvldIn
// Source Path: fir_ds10_onephase/Discrete FIR Filter/Filter/subFilter/FilterTapWvldIn
// Hierarchy Level: 4
// Model version: 2.1
// 
// -------------------------------------------------------------
module FilterTapWvldIn
          (sys_clk,
           enb,
           dinReg2_0_re,
           tapout,
           multVld,
           syncReset,
           tapout_1);


  input   sys_clk;
  input   enb;
  input   signed [15:0] dinReg2_0_re;  // sfix16_En14
  input   signed [33:0] tapout;  // sfix34_En28
  input   multVld;
  input   syncReset;
  output  signed [33:0] tapout_1;  // sfix34_En28


  reg signed [15:0] multIn;  // sfix16_En14
  wire signed [31:0] multOut;  // sfix32_En28
  reg signed [15:0] fTap_din_reg;  // sfix16
  reg signed [31:0] fTap_mult_reg;  // sfix32
  reg signed [33:0] fTap_addout_reg;  // sfix34
  reg signed [15:0] fTap_din_reg_next;  // sfix16_En14
  reg signed [31:0] fTap_mult_reg_next;  // sfix32_En28
  reg signed [33:0] fTap_addout_reg_next;  // sfix34_En28
  reg signed [33:0] tapout_2;  // sfix34_En28
  reg signed [33:0] fTap_add_cast;  // sfix34_En28

  initial begin
    fTap_din_reg = 16'sb0000000000000000;
    fTap_mult_reg = 32'sb00000000000000000000000000000000;
    fTap_addout_reg = 34'sh000000000;
  end

  assign multOut = {{2{multIn[15]}}, {multIn, 14'b00000000000000}};



  // FilterTap
  always @(posedge sys_clk)
    begin : fTap_process
      if (enb) begin
        if (syncReset == 1'b1) begin
          fTap_din_reg <= 16'sb0000000000000000;
          fTap_mult_reg <= 32'sb00000000000000000000000000000000;
          fTap_addout_reg <= 34'sh000000000;
        end
        else begin
          fTap_din_reg <= fTap_din_reg_next;
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
        end
      end
    end

  always @(dinReg2_0_re, fTap_addout_reg, fTap_din_reg, fTap_mult_reg, multOut, multVld,
       tapout) begin
    fTap_add_cast = 34'sh000000000;
    fTap_addout_reg_next = fTap_addout_reg;
    if (multVld) begin
      fTap_add_cast = {{2{fTap_mult_reg[31]}}, fTap_mult_reg};
      fTap_addout_reg_next = fTap_add_cast + tapout;
    end
    fTap_mult_reg_next = multOut;
    fTap_din_reg_next = dinReg2_0_re;
    multIn = fTap_din_reg;
    tapout_2 = fTap_addout_reg;
  end



  assign tapout_1 = tapout_2;

endmodule  // FilterTapWvldIn

