// -------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_onephase\FilterTapPostAdd.v
// Created: 2026-01-24 16:18:43
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapPostAdd
// Source Path: fir_ds10_onephase/Discrete FIR Filter/Filter/subFilter/FilterTapPostAdd
// Hierarchy Level: 4
// Model version: 2.1
// 
// -------------------------------------------------------------
module FilterTapPostAdd
          (sys_clk,
           enb,
           addin,
           multOut,
           multVld,
           syncReset,
           tapout);


  input   sys_clk;
  input   enb;
  input   signed [33:0] addin;  // sfix34_En28
  input   signed [33:0] multOut;  // sfix34_En28
  input   multVld;
  input   syncReset;
  output  signed [33:0] tapout;  // sfix34_En28


  reg signed [33:0] fTap_addout_reg;  // sfix34
  reg signed [33:0] fTap_addout_reg_next;  // sfix34_En28
  reg signed [33:0] tapout_1;  // sfix34_En28

  initial begin
    fTap_addout_reg = 34'sh000000000;
  end

  // FilterTapPostAdd
  always @(posedge sys_clk)
    begin : fTap_process
      if (enb) begin
        if (syncReset == 1'b1) begin
          fTap_addout_reg <= 34'sh000000000;
        end
        else begin
          fTap_addout_reg <= fTap_addout_reg_next;
        end
      end
    end

  always @(addin, fTap_addout_reg, multOut, multVld) begin
    fTap_addout_reg_next = fTap_addout_reg;
    tapout_1 = fTap_addout_reg;
    if (multVld) begin
      fTap_addout_reg_next = addin + multOut;
    end
  end



  assign tapout = tapout_1;

endmodule  // FilterTapPostAdd

