// -------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_onephase\fir_ds10_onephase.v
// Created: 2026-01-24 16:18:43
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-08
// Target subsystem base rate: 1e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// o_data                        ce_out        1e-08
// o_data_vld                    ce_out        1e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fir_ds10_onephase
// Source Path: fir_ds10_onephase
// Hierarchy Level: 0
// Model version: 2.1
// 
// -------------------------------------------------------------
module fir_ds10_onephase
          (sys_clk,
           reset_x,
           sys_clk_en,
           i_data,
           i_data_vld,
           ce_out,
           o_data,
           o_data_vld);


  input   sys_clk;
  input   reset_x;
  input   sys_clk_en;
  input   signed [15:0] i_data;  // sfix16_En14
  input   i_data_vld;
  output  ce_out;
  output  signed [15:0] o_data;  // sfix16_En14
  output  o_data_vld;


  wire enb;
  reg signed [15:0] i_data_1;  // sfix16_En14
  reg  i_data_vld_1;
  wire signed [33:0] Discrete_FIR_Filter_out1;  // sfix34_En28
  wire Discrete_FIR_Filter_out2;
  reg signed [33:0] Discrete_FIR_Filter_out1_1;  // sfix34_En28
  wire [15:0] Bit_Slice_out1;  // uint16
  wire signed [15:0] Data_Type_Conversion1_out1;  // sfix16_En14
  reg  Discrete_FIR_Filter_out2_1;


  assign enb = sys_clk_en;

  always @(posedge sys_clk)
    begin : Discrete_FIR_Filter_in_pipe_process
      if (reset_x == 1'b0) begin
        i_data_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          i_data_1 <= i_data;
        end
      end
    end



  always @(posedge sys_clk)
    begin : Discrete_FIR_Filter_in_pipe_1_process
      if (reset_x == 1'b0) begin
        i_data_vld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          i_data_vld_1 <= i_data_vld;
        end
      end
    end



  Discrete_FIR_Filter u_Discrete_FIR_Filter (.sys_clk(sys_clk),
                                             .reset_x(reset_x),
                                             .enb(sys_clk_en),
                                             .dataIn(i_data_1),  // sfix16_En14
                                             .validIn(i_data_vld_1),
                                             .dataOut(Discrete_FIR_Filter_out1),  // sfix34_En28
                                             .validOut(Discrete_FIR_Filter_out2)
                                             );

  always @(posedge sys_clk)
    begin : Discrete_FIR_Filter_out_pipe_process
      if (reset_x == 1'b0) begin
        Discrete_FIR_Filter_out1_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Discrete_FIR_Filter_out1_1 <= Discrete_FIR_Filter_out1;
        end
      end
    end



  assign Bit_Slice_out1 = Discrete_FIR_Filter_out1_1[32:17];



  assign Data_Type_Conversion1_out1 = Bit_Slice_out1;



  assign o_data = Data_Type_Conversion1_out1;

  always @(posedge sys_clk)
    begin : Discrete_FIR_Filter_out_pipe_1_process
      if (reset_x == 1'b0) begin
        Discrete_FIR_Filter_out2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Discrete_FIR_Filter_out2_1 <= Discrete_FIR_Filter_out2;
        end
      end
    end



  assign o_data_vld = Discrete_FIR_Filter_out2_1;

  assign ce_out = sys_clk_en;

endmodule  // fir_ds10_onephase

