// -------------------------------------------------------------
// 
// File Name: hdlsrc\fir_ds10_onephase\subFilter.v
// Created: 2026-01-24 16:18:43
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subFilter
// Source Path: fir_ds10_onephase/Discrete FIR Filter/Filter/subFilter
// Hierarchy Level: 3
// Model version: 2.1
// 
// -------------------------------------------------------------
module subFilter
          (sys_clk,
           reset_x,
           enb,
           dinReg2_0_re,
           dinRegVld,
           syncReset,
           dout_1_re,
           doutVld);


  input   sys_clk;
  input   reset_x;
  input   enb;
  input   signed [15:0] dinReg2_0_re;  // sfix16_En14
  input   dinRegVld;
  input   syncReset;
  output  signed [33:0] dout_1_re;  // sfix34_En28
  output  doutVld;


  reg  [2:0] intdelay_reg;  // ufix1 [3]
  wire tapoutVld;
  wire signed [33:0] addin;  // sfix34_En28
  reg  [1:0] intdelay_reg_1;  // ufix1 [2]
  wire multVld;
  wire signed [33:0] tapout;  // sfix34_En28
  wire signed [33:0] Symmetry;  // sfix34_En28
  wire signed [33:0] tapout_1;  // sfix34_En28
  wire signed [33:0] Symmetry_1;  // sfix34_En28
  wire signed [33:0] tapout_2;  // sfix34_En28
  wire signed [33:0] Symmetry_2;  // sfix34_En28
  wire signed [33:0] tapout_3;  // sfix34_En28
  wire signed [33:0] Symmetry_3;  // sfix34_En28
  wire signed [33:0] tapout_4;  // sfix34_En28
  wire signed [33:0] Symmetry_4;  // sfix34_En28
  wire signed [33:0] tapout_5;  // sfix34_En28
  wire signed [33:0] Symmetry_5;  // sfix34_En28
  wire signed [33:0] tapout_6;  // sfix34_En28
  wire signed [33:0] Symmetry_6;  // sfix34_En28
  wire signed [33:0] tapout_7;  // sfix34_En28
  wire signed [33:0] Symmetry_7;  // sfix34_En28
  wire signed [33:0] tapout_8;  // sfix34_En28
  wire signed [33:0] Symmetry_8;  // sfix34_En28
  wire signed [33:0] tapout_9;  // sfix34_En28
  wire signed [33:0] tapout_10;  // sfix34_En28
  wire signed [33:0] Symmetry_9;  // sfix34_En28
  wire signed [33:0] tapout_11;  // sfix34_En28
  wire signed [33:0] Symmetry_10;  // sfix34_En28
  wire signed [33:0] tapout_12;  // sfix34_En28
  wire signed [33:0] Symmetry_11;  // sfix34_En28
  wire signed [33:0] tapout_13;  // sfix34_En28
  wire signed [33:0] Symmetry_12;  // sfix34_En28
  wire signed [33:0] tapout_14;  // sfix34_En28
  wire signed [33:0] Symmetry_13;  // sfix34_En28
  wire signed [33:0] tapout_15;  // sfix34_En28
  wire signed [33:0] Symmetry_14;  // sfix34_En28
  wire signed [33:0] tapout_16;  // sfix34_En28
  wire signed [33:0] Symmetry_15;  // sfix34_En28
  wire signed [33:0] tapout_17;  // sfix34_En28
  wire signed [33:0] Symmetry_16;  // sfix34_En28
  wire signed [33:0] tapout_18;  // sfix34_En28
  wire signed [33:0] Symmetry_17;  // sfix34_En28
  wire signed [33:0] tapout_19;  // sfix34_En28
  wire signed [33:0] Symmetry_18;  // sfix34_En28
  wire signed [33:0] tapout_20;  // sfix34_En28
  wire signed [33:0] Symmetry_19;  // sfix34_En28
  wire signed [33:0] tapout_21;  // sfix34_En28
  wire signed [33:0] Symmetry_20;  // sfix34_En28
  wire signed [33:0] tapout_22;  // sfix34_En28
  wire signed [33:0] Symmetry_21;  // sfix34_En28
  wire signed [33:0] tapout_23;  // sfix34_En28
  wire signed [33:0] Symmetry_22;  // sfix34_En28
  wire signed [33:0] tapout_24;  // sfix34_En28
  wire signed [33:0] Symmetry_23;  // sfix34_En28
  wire signed [33:0] tapout_25;  // sfix34_En28
  wire signed [33:0] Symmetry_24;  // sfix34_En28
  wire signed [33:0] tapout_26;  // sfix34_En28
  wire signed [33:0] Symmetry_25;  // sfix34_En28
  wire signed [33:0] tapout_27;  // sfix34_En28
  wire signed [33:0] Symmetry_26;  // sfix34_En28
  wire signed [33:0] tapout_28;  // sfix34_En28
  wire signed [33:0] Symmetry_27;  // sfix34_En28
  wire signed [33:0] tapout_29;  // sfix34_En28
  wire signed [33:0] Symmetry_28;  // sfix34_En28
  wire signed [33:0] tapout_30;  // sfix34_En28
  wire signed [33:0] tapout_31;  // sfix34_En28
  wire signed [33:0] tapout_32;  // sfix34_En28
  wire signed [33:0] tapout_33;  // sfix34_En28
  wire signed [33:0] tapout_34;  // sfix34_En28
  wire signed [33:0] tapout_35;  // sfix34_En28
  wire signed [33:0] tapout_36;  // sfix34_En28
  wire signed [33:0] tapout_37;  // sfix34_En28
  wire signed [33:0] tapout_38;  // sfix34_En28
  wire signed [33:0] tapout_39;  // sfix34_En28
  wire signed [33:0] tapout_40;  // sfix34_En28
  wire signed [33:0] tapout_41;  // sfix34_En28
  wire signed [33:0] tapout_42;  // sfix34_En28
  wire signed [33:0] tapout_43;  // sfix34_En28
  wire signed [33:0] tapout_44;  // sfix34_En28
  wire signed [33:0] tapout_45;  // sfix34_En28
  wire signed [33:0] tapout_46;  // sfix34_En28
  wire signed [33:0] tapout_47;  // sfix34_En28
  wire signed [33:0] tapout_48;  // sfix34_En28
  wire signed [33:0] tapout_49;  // sfix34_En28
  wire signed [33:0] tapout_50;  // sfix34_En28
  wire signed [33:0] tapout_51;  // sfix34_En28
  wire signed [33:0] tapout_52;  // sfix34_En28
  wire signed [33:0] tapout_53;  // sfix34_En28
  wire signed [33:0] tapout_54;  // sfix34_En28
  wire signed [33:0] tapout_55;  // sfix34_En28
  wire signed [33:0] tapout_56;  // sfix34_En28
  wire signed [33:0] tapout_57;  // sfix34_En28
  wire signed [33:0] tapout_58;  // sfix34_En28
  wire signed [33:0] tapout_59;  // sfix34_En28
  wire signed [33:0] tapout_60;  // sfix34_En28
  wire signed [33:0] muxOut;  // sfix34_En28
  reg signed [33:0] dout_1_re_1;  // sfix34_En28
  reg  doutVld_1;


  always @(posedge sys_clk)
    begin : intdelay_process
      if (reset_x == 1'b0) begin
        intdelay_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg <= {3{1'b0}};
          end
          else begin
            intdelay_reg[0] <= dinRegVld;
            intdelay_reg[32'sd2:32'sd1] <= intdelay_reg[32'sd1:32'sd0];
          end
        end
      end
    end

  assign tapoutVld = intdelay_reg[2];



  assign addin = 34'sh000000000;



  always @(posedge sys_clk)
    begin : intdelay_1_process
      if (reset_x == 1'b0) begin
        intdelay_reg_1 <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg_1 <= {2{1'b0}};
          end
          else begin
            intdelay_reg_1[0] <= dinRegVld;
            intdelay_reg_1[1] <= intdelay_reg_1[0];
          end
        end
      end
    end

  assign multVld = intdelay_reg_1[1];



  FilterTapWMultOutCSD u_FTapMultOutCSD_1 (.sys_clk(sys_clk),
                                           .enb(enb),
                                           .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                           .addin(addin),  // sfix34_En28
                                           .multVld(multVld),
                                           .syncReset(syncReset),
                                           .tapout(tapout),  // sfix34_En28
                                           .multOut(Symmetry)  // sfix34_En28
                                           );

  FilterTapWMultOutCSD_block u_FTapMultOutCSD_2 (.sys_clk(sys_clk),
                                                 .enb(enb),
                                                 .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                 .tapout(tapout),  // sfix34_En28
                                                 .multVld(multVld),
                                                 .syncReset(syncReset),
                                                 .tapout_1(tapout_1),  // sfix34_En28
                                                 .multOut(Symmetry_1)  // sfix34_En28
                                                 );

  FilterTapWMultOutCSD_block1 u_FTapMultOutCSD_3 (.sys_clk(sys_clk),
                                                  .enb(enb),
                                                  .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                  .tapout(tapout_1),  // sfix34_En28
                                                  .multVld(multVld),
                                                  .syncReset(syncReset),
                                                  .tapout_1(tapout_2),  // sfix34_En28
                                                  .multOut(Symmetry_2)  // sfix34_En28
                                                  );

  FilterTapWMultOutCSD_block2 u_FTapMultOutCSD_4 (.sys_clk(sys_clk),
                                                  .enb(enb),
                                                  .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                  .tapout(tapout_2),  // sfix34_En28
                                                  .multVld(multVld),
                                                  .syncReset(syncReset),
                                                  .tapout_1(tapout_3),  // sfix34_En28
                                                  .multOut(Symmetry_3)  // sfix34_En28
                                                  );

  FilterTapWMultOutCSD_block3 u_FTapMultOutCSD_5 (.sys_clk(sys_clk),
                                                  .enb(enb),
                                                  .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                  .tapout(tapout_3),  // sfix34_En28
                                                  .multVld(multVld),
                                                  .syncReset(syncReset),
                                                  .tapout_1(tapout_4),  // sfix34_En28
                                                  .multOut(Symmetry_4)  // sfix34_En28
                                                  );

  FilterTapWMultOutCSD_block4 u_FTapMultOutCSD_6 (.sys_clk(sys_clk),
                                                  .enb(enb),
                                                  .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                  .tapout(tapout_4),  // sfix34_En28
                                                  .multVld(multVld),
                                                  .syncReset(syncReset),
                                                  .tapout_1(tapout_5),  // sfix34_En28
                                                  .multOut(Symmetry_5)  // sfix34_En28
                                                  );

  FilterTapWMultOutCSD_block5 u_FTapMultOutCSD_7 (.sys_clk(sys_clk),
                                                  .enb(enb),
                                                  .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                  .tapout(tapout_5),  // sfix34_En28
                                                  .multVld(multVld),
                                                  .syncReset(syncReset),
                                                  .tapout_1(tapout_6),  // sfix34_En28
                                                  .multOut(Symmetry_6)  // sfix34_En28
                                                  );

  FilterTapWMultOutCSD_block6 u_FTapMultOutCSD_8 (.sys_clk(sys_clk),
                                                  .enb(enb),
                                                  .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                  .tapout(tapout_6),  // sfix34_En28
                                                  .multVld(multVld),
                                                  .syncReset(syncReset),
                                                  .tapout_1(tapout_7),  // sfix34_En28
                                                  .multOut(Symmetry_7)  // sfix34_En28
                                                  );

  FilterTapWMultOutCSD_block7 u_FTapMultOutCSD_9 (.sys_clk(sys_clk),
                                                  .enb(enb),
                                                  .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                  .tapout(tapout_7),  // sfix34_En28
                                                  .multVld(multVld),
                                                  .syncReset(syncReset),
                                                  .tapout_1(tapout_8),  // sfix34_En28
                                                  .multOut(Symmetry_8)  // sfix34_En28
                                                  );

  FilterTapPostAdd u_FTapPostAdd_10 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_8),  // sfix34_En28
                                     .multOut(Symmetry_8),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_9)  // sfix34_En28
                                     );

  FilterTapWMultOutCSD_block8 u_FTapMultOutCSD_11 (.sys_clk(sys_clk),
                                                   .enb(enb),
                                                   .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                   .tapout(tapout_9),  // sfix34_En28
                                                   .multVld(multVld),
                                                   .syncReset(syncReset),
                                                   .tapout_1(tapout_10),  // sfix34_En28
                                                   .multOut(Symmetry_9)  // sfix34_En28
                                                   );

  FilterTapWMultOutCSD_block9 u_FTapMultOutCSD_12 (.sys_clk(sys_clk),
                                                   .enb(enb),
                                                   .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                   .tapout(tapout_10),  // sfix34_En28
                                                   .multVld(multVld),
                                                   .syncReset(syncReset),
                                                   .tapout_1(tapout_11),  // sfix34_En28
                                                   .multOut(Symmetry_10)  // sfix34_En28
                                                   );

  FilterTapWMultOutCSD_block10 u_FTapMultOutCSD_13 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_11),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_12),  // sfix34_En28
                                                    .multOut(Symmetry_11)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block11 u_FTapMultOutCSD_14 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_12),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_13),  // sfix34_En28
                                                    .multOut(Symmetry_12)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block12 u_FTapMultOutCSD_15 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_13),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_14),  // sfix34_En28
                                                    .multOut(Symmetry_13)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block13 u_FTapMultOutCSD_16 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_14),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_15),  // sfix34_En28
                                                    .multOut(Symmetry_14)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block14 u_FTapMultOutCSD_17 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_15),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_16),  // sfix34_En28
                                                    .multOut(Symmetry_15)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block15 u_FTapMultOutCSD_18 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_16),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_17),  // sfix34_En28
                                                    .multOut(Symmetry_16)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block16 u_FTapMultOutCSD_19 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_17),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_18),  // sfix34_En28
                                                    .multOut(Symmetry_17)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block17 u_FTapMultOutCSD_20 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_18),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_19),  // sfix34_En28
                                                    .multOut(Symmetry_18)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block18 u_FTapMultOutCSD_21 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_19),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_20),  // sfix34_En28
                                                    .multOut(Symmetry_19)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block19 u_FTapMultOutCSD_22 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_20),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_21),  // sfix34_En28
                                                    .multOut(Symmetry_20)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block20 u_FTapMultOutCSD_23 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_21),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_22),  // sfix34_En28
                                                    .multOut(Symmetry_21)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block21 u_FTapMultOutCSD_24 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_22),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_23),  // sfix34_En28
                                                    .multOut(Symmetry_22)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block22 u_FTapMultOutCSD_25 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_23),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_24),  // sfix34_En28
                                                    .multOut(Symmetry_23)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block23 u_FTapMultOutCSD_26 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_24),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_25),  // sfix34_En28
                                                    .multOut(Symmetry_24)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block24 u_FTapMultOutCSD_27 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_25),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_26),  // sfix34_En28
                                                    .multOut(Symmetry_25)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block25 u_FTapMultOutCSD_28 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_26),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_27),  // sfix34_En28
                                                    .multOut(Symmetry_26)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block26 u_FTapMultOutCSD_29 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_27),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_28),  // sfix34_En28
                                                    .multOut(Symmetry_27)  // sfix34_En28
                                                    );

  FilterTapWMultOutCSD_block27 u_FTapMultOutCSD_30 (.sys_clk(sys_clk),
                                                    .enb(enb),
                                                    .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                                    .tapout(tapout_28),  // sfix34_En28
                                                    .multVld(multVld),
                                                    .syncReset(syncReset),
                                                    .tapout_1(tapout_29),  // sfix34_En28
                                                    .multOut(Symmetry_28)  // sfix34_En28
                                                    );

  FilterTapWvldIn u_FTapCSD_31 (.sys_clk(sys_clk),
                                .enb(enb),
                                .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                .tapout(tapout_29),  // sfix34_En28
                                .multVld(multVld),
                                .syncReset(syncReset),
                                .tapout_1(tapout_30)  // sfix34_En28
                                );

  FilterTapPostAdd u_FTapPostAdd_32 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_30),  // sfix34_En28
                                     .multOut(Symmetry_28),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_31)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_33 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_31),  // sfix34_En28
                                     .multOut(Symmetry_27),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_32)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_34 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_32),  // sfix34_En28
                                     .multOut(Symmetry_26),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_33)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_35 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_33),  // sfix34_En28
                                     .multOut(Symmetry_25),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_34)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_36 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_34),  // sfix34_En28
                                     .multOut(Symmetry_24),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_35)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_37 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_35),  // sfix34_En28
                                     .multOut(Symmetry_23),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_36)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_38 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_36),  // sfix34_En28
                                     .multOut(Symmetry_22),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_37)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_39 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_37),  // sfix34_En28
                                     .multOut(Symmetry_21),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_38)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_40 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_38),  // sfix34_En28
                                     .multOut(Symmetry_20),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_39)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_41 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_39),  // sfix34_En28
                                     .multOut(Symmetry_19),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_40)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_42 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_40),  // sfix34_En28
                                     .multOut(Symmetry_18),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_41)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_43 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_41),  // sfix34_En28
                                     .multOut(Symmetry_17),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_42)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_44 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_42),  // sfix34_En28
                                     .multOut(Symmetry_16),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_43)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_45 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_43),  // sfix34_En28
                                     .multOut(Symmetry_15),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_44)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_46 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_44),  // sfix34_En28
                                     .multOut(Symmetry_14),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_45)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_47 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_45),  // sfix34_En28
                                     .multOut(Symmetry_13),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_46)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_48 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_46),  // sfix34_En28
                                     .multOut(Symmetry_12),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_47)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_49 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_47),  // sfix34_En28
                                     .multOut(Symmetry_11),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_48)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_50 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_48),  // sfix34_En28
                                     .multOut(Symmetry_10),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_49)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_51 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_49),  // sfix34_En28
                                     .multOut(Symmetry_9),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_50)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_52 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_50),  // sfix34_En28
                                     .multOut(Symmetry_8),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_51)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_53 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_51),  // sfix34_En28
                                     .multOut(Symmetry_8),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_52)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_54 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_52),  // sfix34_En28
                                     .multOut(Symmetry_7),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_53)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_55 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_53),  // sfix34_En28
                                     .multOut(Symmetry_6),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_54)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_56 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_54),  // sfix34_En28
                                     .multOut(Symmetry_5),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_55)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_57 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_55),  // sfix34_En28
                                     .multOut(Symmetry_4),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_56)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_58 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_56),  // sfix34_En28
                                     .multOut(Symmetry_3),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_57)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_59 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_57),  // sfix34_En28
                                     .multOut(Symmetry_2),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_58)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_60 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_58),  // sfix34_En28
                                     .multOut(Symmetry_1),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_59)  // sfix34_En28
                                     );

  FilterTapPostAdd u_FTapPostAdd_61 (.sys_clk(sys_clk),
                                     .enb(enb),
                                     .addin(tapout_59),  // sfix34_En28
                                     .multOut(Symmetry),  // sfix34_En28
                                     .multVld(multVld),
                                     .syncReset(syncReset),
                                     .tapout(tapout_60)  // sfix34_En28
                                     );

  assign muxOut = (tapoutVld == 1'b0 ? 34'sh000000000 :
              tapout_60);



  always @(posedge sys_clk)
    begin : intdelay_2_process
      if (reset_x == 1'b0) begin
        dout_1_re_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dout_1_re_1 <= 34'sh000000000;
          end
          else begin
            dout_1_re_1 <= muxOut;
          end
        end
      end
    end



  always @(posedge sys_clk)
    begin : intdelay_3_process
      if (reset_x == 1'b0) begin
        doutVld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            doutVld_1 <= 1'b0;
          end
          else begin
            doutVld_1 <= tapoutVld;
          end
        end
      end
    end



  assign dout_1_re = dout_1_re_1;

  assign doutVld = doutVld_1;

endmodule  // subFilter

